/**
 * pdfUtils.js — Shared helper for generating single-record and summary PDFs
 * Used by CompanyPurchase, DealerPurchase, LocalPurchase, Sales, and Inventory pages.
 */

const SHOWROOM = "Ammar Autos";
const SHOWROOM_SUB = "Bike Showroom Management System";

/* ─── helpers ─────────────────────────────────────────────── */
function fmt(n) {
  return n != null && n !== "" ? `Rs. ${Number(n).toLocaleString()}` : "—";
}

function fmtDate(val) {
  if (!val) return "—";
  const d = val?.seconds ? new Date(val.seconds * 1000) : new Date(val);
  if (isNaN(d)) return "—";
  return d.toLocaleDateString("en-PK") + " " + d.toLocaleTimeString("en-PK", { hour: "2-digit", minute: "2-digit" });
}

function row(label, value, accent = false) {
  return `
    <tr>
      <td style="padding:8px 12px;font-size:12px;font-weight:600;color:#64748b;width:40%;border-bottom:1px solid #f1f5f9;white-space:nowrap;">${label}</td>
      <td style="padding:8px 12px;font-size:12px;color:${accent ? "#059669" : "#1e293b"};font-weight:${accent ? "700" : "500"};border-bottom:1px solid #f1f5f9;">${value || "—"}</td>
    </tr>`;
}

function section(title, color, rows) {
  return `
    <div style="margin-bottom:20px;">
      <div style="background:${color};color:white;padding:8px 14px;border-radius:8px 8px 0 0;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;">${title}</div>
      <table style="width:100%;border-collapse:collapse;border:1px solid #e2e8f0;border-top:none;border-radius:0 0 8px 8px;overflow:hidden;">
        ${rows}
      </table>
    </div>`;
}

function printWindow(title, body) {
  const win = window.open("", "_blank", "width=850,height=700");
  win.document.write(`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>${title}</title>
  <style>
    *{box-sizing:border-box;margin:0;padding:0;font-family:'Segoe UI',Arial,sans-serif;}
    body{background:#fff;padding:28px;color:#1e293b;}
    @media print{
      body{padding:16px;}
      .no-print{display:none!important;}
    }
  </style>
</head>
<body>
  <!-- Print Button -->
  <div class="no-print" style="text-align:right;margin-bottom:16px;">
    <button onclick="window.print()" style="padding:8px 20px;background:#0f172a;color:white;border:none;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;">
      🖨️ Print / Save as PDF
    </button>
  </div>
  ${body}
  <div style="margin-top:28px;padding-top:14px;border-top:1px solid #e2e8f0;text-align:center;font-size:11px;color:#94a3b8;">
    Generated by ${SHOWROOM} — ${new Date().toLocaleDateString("en-PK", { year: "numeric", month: "long", day: "numeric" })}
  </div>
</body>
</html>`);
  win.document.close();
}

/* ─── PURCHASE PDF ─────────────────────────────────────────── */
export function downloadPurchasePDF(p) {
  const categoryLabel =
    p.category === "company" ? "Company Purchase" :
    p.category === "dealer" ? "Dealer Purchase" :
    "Local Customer Purchase";

  const body = `
    <!-- Header -->
    <div style="background:linear-gradient(135deg,#0f172a 0%,#1e3a5f 100%);color:white;padding:24px 28px;border-radius:14px;margin-bottom:24px;display:flex;align-items:center;justify-content:space-between;">
      <div>
        <div style="font-size:22px;font-weight:800;letter-spacing:-0.5px;">🏍️ ${SHOWROOM}</div>
        <div style="font-size:11px;opacity:0.7;margin-top:4px;">${SHOWROOM_SUB}</div>
        <div style="margin-top:8px;display:inline-block;background:rgba(255,255,255,0.15);padding:3px 10px;border-radius:20px;font-size:10px;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;">${categoryLabel}</div>
      </div>
      <div style="text-align:right;">
        <div style="font-size:10px;opacity:0.7;">Date</div>
        <div style="font-size:14px;font-weight:700;">${new Date().toLocaleDateString("en-PK")}</div>
        <div style="font-size:10px;opacity:0.7;margin-top:6px;">Record ID</div>
        <div style="font-size:11px;font-weight:600;opacity:0.9;">${p.id || "—"}</div>
      </div>
    </div>

    ${section("👤 Customer / Supplier Details", "#334155",
      row("Name", p.customerName) +
      row("Father's Name", p.customerFatherName) +
      row("Phone", p.customerNo) +
      row("CNIC", p.cnicNumber) +
      row("Current Address", p.currentAddress) +
      row("Permanent Address", p.permanentAddress)
    )}

    ${section("🏍️ Bike Details", "#1e40af",
      row("Company", p.bikeCompany) +
      row("Model", p.bikeModel) +
      row("Engine CC", p.bikeCC) +
      row("Color", p.bikeColor) +
      row("Registration No.", p.registrationStatus === "AFR" ? "AFR" : p.registrationNo) +
      row("Chasis No.", p.chasisStatus === "AFR" ? "AFR" : p.chasisNo) +
      row("Engine No.", p.engineStatus === "AFR" ? "AFR" : p.engineNo)
    )}

    ${section("💰 Financial Details", "#065f46",
      row("Actual Amount", fmt(p.actualAmount), true) +
      row("Amount Remaining", fmt(p.amountRemaining)) +
      row("Additional Expense", fmt(p.additionalExpense)) +
      row("Purchase Date", fmtDate(p.purchaseDateTime) || p.purchaseDate) +
      row("Approval Status", p.approved ? "✅ Approved" : "⏳ Pending")
    )}
  `;

  printWindow(`${SHOWROOM} — Purchase Receipt`, body);
}

/* ─── SALE PDF ─────────────────────────────────────────────── */
export function downloadSalePDF(s) {
  const remaining = Math.max(
    0,
    Number(s.totalSaleAmount || 0) - Number(s.advanceReceived || 0) - Number(s.paidInstallments || 0)
  );

  const body = `
    <!-- Header -->
    <div style="background:linear-gradient(135deg,#064e3b 0%,#065f46 100%);color:white;padding:24px 28px;border-radius:14px;margin-bottom:24px;display:flex;align-items:center;justify-content:space-between;">
      <div>
        <div style="font-size:22px;font-weight:800;letter-spacing:-0.5px;">🏍️ ${SHOWROOM}</div>
        <div style="font-size:11px;opacity:0.7;margin-top:4px;">${SHOWROOM_SUB}</div>
        <div style="margin-top:8px;display:inline-block;background:rgba(255,255,255,0.15);padding:3px 10px;border-radius:20px;font-size:10px;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;">
          Sale Receipt — ${s.saleType === "installment" ? "Installment" : "Cash"}
        </div>
      </div>
      <div style="text-align:right;">
        <div style="font-size:10px;opacity:0.7;">Sale Date</div>
        <div style="font-size:14px;font-weight:700;">${fmtDate(s.saleDateTime)}</div>
        <div style="font-size:10px;opacity:0.7;margin-top:6px;">Record ID</div>
        <div style="font-size:11px;font-weight:600;opacity:0.9;">${s.id || "—"}</div>
      </div>
    </div>

    ${section("🏍️ Bike Details", "#1e40af",
      row("Registration No.", s.registrationStatus === "AFR" ? "AFR" : s.registrationNo) +
      row("Company", s.bikeCompany) +
      row("Model", s.bikeModel) +
      row("Chasis No.", s.chasisNo) +
      row("Engine No.", s.engineNo)
    )}

    ${section("👤 Buyer Details", "#334155",
      row("Buyer Name", s.buyerName) +
      row("Father's Name", s.buyerFatherName) +
      row("CNIC", s.buyerCnic) +
      row("Current Address", s.buyerCurrentAddress) +
      row("Permanent Address", s.buyerPermanentAddress)
    )}

    ${section("🤝 Seller Details", "#4c1d95",
      row("Seller Name", s.salerName) +
      row("Seller Phone", s.salerNumber) +
      row("Seller CNIC", s.salerCnic) +
      row("Seller Address", s.salerAddress)
    )}

    ${section("💰 Financial Details", "#065f46",
      row("Total Sale Amount", fmt(s.totalSaleAmount), true) +
      row("Advance Received", fmt(s.advanceReceived)) +
      row("Installments Paid", fmt(s.paidInstallments)) +
      row("Balance Remaining", fmt(s.amountRemaining ?? (Number(s.totalSaleAmount || 0) - Number(s.advanceReceived || 0)))) +
      (s.saleType === "installment" ? (
        row("Installment Months", s.installmentMonths || "—") +
        row("Per Month", fmt(s.perMonthInstallment)) +
        row("Start Date", fmtDate(s.installmentStartDate)) +
        (s.installmentDescription ? row("Installment Plan Notes", s.installmentDescription) : "")
      ) : "")
    )}

    ${s.saleType === "installment" && Array.isArray(s.installments) && s.installments.length > 0 ? `
      <div style="margin-top:20px;">
        <div style="background:#0f172a;color:white;padding:8px 14px;border-radius:8px 8px 0 0;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;">
          📅 Custom Installment Schedule
        </div>
        <table style="width:100%;border-collapse:collapse;border:1px solid #e2e8f0;border-top:none;border-radius:0 0 8px 8px;overflow:hidden;font-size:11px;">
          <thead>
            <tr style="background:#f8fafc;border-bottom:1px solid #e2e8f0;text-align:left;color:#64748b;">
              <th style="padding:8px 12px;">#</th>
              <th style="padding:8px 12px;">Due Date</th>
              <th style="padding:8px 12px;">Description</th>
              <th style="padding:8px 12px;text-align:right;">Amount</th>
              <th style="padding:8px 12px;text-align:center;">Status</th>
            </tr>
          </thead>
          <tbody>
            ${s.installments.map((inst, idx) => `
              <tr style="border-bottom:1px solid #f1f5f9;">
                <td style="padding:8px 12px;font-weight:600;color:#64748b;">${inst.monthNumber || idx + 1}</td>
                <td style="padding:8px 12px;color:#1e293b;">${fmtDate(inst.dueDate)}</td>
                <td style="padding:8px 12px;color:#475569;">${inst.description || `Installment #${idx + 1}`}</td>
                <td style="padding:8px 12px;text-align:right;font-weight:700;color:#0f172a;">${fmt(inst.amount)}</td>
                <td style="padding:8px 12px;text-align:center;font-weight:700;color:${inst.paid ? "#059669" : "#d97706"}; font-size:10px;">
                  ${inst.paid ? "PAID" : "PENDING"}
                </td>
              </tr>
            `).join("")}
          </tbody>
        </table>
      </div>
    ` : ""}
  `;

  printWindow(`${SHOWROOM} — Sale Receipt`, body);
}

/* ─── INVENTORY PDF ────────────────────────────────────────── */
export function downloadInventoryPDF(inventory = [], summary = {}) {
  const rows = inventory.map((item, idx) => `
    <tr style="border-bottom:1px solid #f1f5f9;">
      <td style="padding:10px 12px;font-size:12px;color:#64748b;">${idx + 1}</td>
      <td style="padding:10px 12px;font-size:12px;font-weight:700;color:#1e293b;">${[item.bikeCompany, item.bikeModel].filter(Boolean).join(" ") || "—"}</td>
      <td style="padding:10px 12px;font-size:12px;color:#475569;">${item.registrationNo || "—"}</td>
      <td style="padding:10px 12px;font-size:12px;color:#475569;">${item.chasisNo || "—"}</td>
      <td style="padding:10px 12px;font-size:12px;color:#475569;">${item.engineNo || "—"}</td>
      <td style="padding:10px 12px;font-size:12px;font-weight:700;color:#059669;">${fmt(item.actualAmount)}</td>
      <td style="padding:10px 12px;font-size:12px;font-weight:700;color:#dc2626;">${fmt(item.amountRemaining)}</td>
      <td style="padding:10px 12px;font-size:12px;color:#475569;">${item.customerName || "—"}</td>
    </tr>
  `).join("");

  const body = `
    <!-- Header -->
    <div style="background:linear-gradient(135deg,#0f172a 0%,#1e293b 100%);color:white;padding:24px 28px;border-radius:14px;margin-bottom:24px;display:flex;align-items:center;justify-content:space-between;">
      <div>
        <div style="font-size:22px;font-weight:800;letter-spacing:-0.5px;">🏍️ ${SHOWROOM}</div>
        <div style="font-size:11px;opacity:0.7;margin-top:4px;">${SHOWROOM_SUB}</div>
        <div style="margin-top:8px;display:inline-block;background:rgba(255,255,255,0.15);padding:3px 10px;border-radius:20px;font-size:10px;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;">
          Inventory & Stock Summary Report
        </div>
      </div>
      <div style="text-align:right;">
        <div style="font-size:10px;opacity:0.7;">Report Date</div>
        <div style="font-size:14px;font-weight:700;">${new Date().toLocaleDateString("en-PK")}</div>
      </div>
    </div>

    <!-- Summary Cards -->
    <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:24px;">
      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:16px;text-align:center;">
        <div style="font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Unsold Purchased Bikes</div>
        <div style="font-size:20px;font-weight:800;color:#0f172a;margin-top:4px;">${summary.totalPurchased || 0}</div>
      </div>
      <div style="background:#ecfdf5;border:1px solid #a7f3d0;border-radius:10px;padding:16px;text-align:center;">
        <div style="font-size:10px;font-weight:700;color:#047857;text-transform:uppercase;">Total Inventory Value</div>
        <div style="font-size:20px;font-weight:800;color:#059669;margin-top:4px;">${fmt(summary.totalPurchaseValue)}</div>
      </div>
      <div style="background:#fff1f2;border:1px solid #fecdd3;border-radius:10px;padding:16px;text-align:center;">
        <div style="font-size:10px;font-weight:700;color:#be123c;text-transform:uppercase;">Remaining Payment</div>
        <div style="font-size:20px;font-weight:800;color:#e11d48;margin-top:4px;">${fmt(summary.remainingBalance)}</div>
      </div>
    </div>

    <!-- Table -->
    <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;color:#64748b;margin-bottom:10px;">Available Inventory List</div>
    <table style="width:100%;border-collapse:collapse;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;">
      <thead>
        <tr style="background:#f8fafc;border-bottom:1px solid #e2e8f0;">
          <th style="padding:10px 12px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">#</th>
          <th style="padding:10px 12px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Bike Model</th>
          <th style="padding:10px 12px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Reg No</th>
          <th style="padding:10px 12px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Chasis No</th>
          <th style="padding:10px 12px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Engine No</th>
          <th style="padding:10px 12px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Purchase Price</th>
          <th style="padding:10px 12px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Remaining</th>
          <th style="padding:10px 12px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Seller Name</th>
        </tr>
      </thead>
      <tbody>
        ${rows || `<tr><td colspan="8" style="text-align:center;padding:24px;color:#94a3b8;font-size:12px;">No inventory items available.</td></tr>`}
      </tbody>
    </table>
  `;

  printWindow(`${SHOWROOM} — Inventory Summary Report`, body);
}
