/**
 * pdfUtils.js — Shared helper for generating single-record and summary PDFs
 * Used by CompanyPurchase, DealerPurchase, LocalPurchase, Sales, Inventory, and Daily Expense pages.
 */

const SHOWROOM = "Ammar Autos";
const SHOWROOM_SUB = "Bike Showroom Management System";

/* ─── helpers ─────────────────────────────────────────────── */
function fmt(n) {
  return n != null && n !== "" ? `Rs. ${Number(n).toLocaleString()}` : "—";
}

function fmtDate(val) {
  if (!val) return "—";
  const d = val?.seconds ? new Date(val.seconds * 1000) : new Date(val);
  if (isNaN(d)) return "—";
  return d.toLocaleDateString("en-PK") + " " + d.toLocaleTimeString("en-PK", { hour: "2-digit", minute: "2-digit" });
}

function row(label, value, accent = false) {
  return `
    <tr>
      <td style="padding:8px 12px;font-size:12px;font-weight:600;color:#64748b;width:40%;border-bottom:1px solid #f1f5f9;white-space:nowrap;">${label}</td>
      <td style="padding:8px 12px;font-size:12px;color:${accent ? "#059669" : "#1e293b"};font-weight:${accent ? "700" : "500"};border-bottom:1px solid #f1f5f9;">${value || "—"}</td>
    </tr>`;
}

function section(title, color, rows) {
  return `
    <div style="margin-bottom:20px;">
      <div style="background:${color};color:white;padding:8px 14px;border-radius:8px 8px 0 0;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;">${title}</div>
      <table style="width:100%;border-collapse:collapse;border:1px solid #e2e8f0;border-top:none;border-radius:0 0 8px 8px;overflow:hidden;">
        ${rows}
      </table>
    </div>`;
}

function printWindow(title, body) {
  const win = window.open("", "_blank", "width=850,height=700");
  win.document.write(`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>${title}</title>
  <style>
    *{box-sizing:border-box;margin:0;padding:0;font-family:'Segoe UI',Arial,sans-serif;}
    body{background:#fff;padding:28px;color:#1e293b;}
    @media print{
      body{padding:16px;}
      .no-print{display:none!important;}
    }
  </style>
</head>
<body>
  <!-- Print Button -->
  <div class="no-print" style="text-align:right;margin-bottom:16px;">
    <button onclick="window.print()" style="padding:8px 20px;background:#0f172a;color:white;border:none;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;">
      🖨️ Print / Save as PDF
    </button>
  </div>
  ${body}
  <div style="margin-top:28px;padding-top:14px;border-top:1px solid #e2e8f0;text-align:center;font-size:11px;color:#94a3b8;">
    Generated by ${SHOWROOM} — ${new Date().toLocaleDateString("en-PK", { year: "numeric", month: "long", day: "numeric" })}
  </div>
</body>
</html>`);
  win.document.close();
}

/* ─── PURCHASE PDF ─────────────────────────────────────────── */
export function downloadPurchasePDF(p) {
  const categoryLabel =
    p.category === "company" ? "Company Purchase" :
    p.category === "dealer" ? "Dealer Purchase" :
    "Local Customer Purchase";

  const body = `
    <!-- Header -->
    <div style="background:linear-gradient(135deg,#0f172a 0%,#1e3a5f 100%);color:white;padding:24px 28px;border-radius:14px;margin-bottom:24px;display:flex;align-items:center;justify-content:space-between;">
      <div>
        <div style="font-size:22px;font-weight:800;letter-spacing:-0.5px;">🏍️ ${SHOWROOM}</div>
        <div style="font-size:11px;opacity:0.7;margin-top:4px;">${SHOWROOM_SUB}</div>
        <div style="margin-top:8px;display:inline-block;background:rgba(255,255,255,0.15);padding:3px 10px;border-radius:20px;font-size:10px;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;">${categoryLabel}</div>
      </div>
      <div style="text-align:right;">
        <div style="font-size:10px;opacity:0.7;">Date</div>
        <div style="font-size:14px;font-weight:700;">${new Date().toLocaleDateString("en-PK")}</div>
        <div style="font-size:10px;opacity:0.7;margin-top:6px;">Record ID</div>
        <div style="font-size:11px;font-weight:600;opacity:0.9;">${p.id || "—"}</div>
      </div>
    </div>

    ${section("👤 Customer / Supplier Details", "#334155",
      row("Name", p.customerName) +
      row("Father's Name", p.customerFatherName) +
      row("Phone", p.customerNo) +
      row("CNIC", p.cnicNumber) +
      row("Current Address", p.currentAddress) +
      row("Permanent Address", p.permanentAddress)
    )}

    ${section("🏍️ Bike Details", "#1e40af",
      row("Company", p.bikeCompany) +
      row("Model", p.bikeModel) +
      row("Engine CC", p.bikeCC) +
      row("Color", p.bikeColor) +
      row("Registration No.", p.registrationStatus === "AFR" ? "AFR" : p.registrationNo) +
      row("Chasis No.", p.chasisStatus === "AFR" ? "AFR" : p.chasisNo) +
      row("Engine No.", p.engineStatus === "AFR" ? "AFR" : p.engineNo)
    )}

    ${section("💰 Financial Details", "#065f46",
      row("Actual Amount", fmt(p.actualAmount), true) +
      row("Amount Remaining", fmt(p.amountRemaining)) +
      row("Additional Expense", fmt(p.additionalExpense)) +
      row("Purchase Date", fmtDate(p.purchaseDateTime) || p.purchaseDate) +
      row("Approval Status", p.approved ? "✅ Approved" : "⏳ Pending")
    )}
  `;

  printWindow(`${SHOWROOM} — Purchase Receipt`, body);
}

/* ─── SALE PDF ─────────────────────────────────────────────── */
export function downloadSalePDF(s) {
  const remaining = Math.max(
    0,
    Number(s.totalSaleAmount || 0) - Number(s.advanceReceived || 0) - Number(s.paidInstallments || 0)
  );

  const body = `
    <!-- Header -->
    <div style="background:linear-gradient(135deg,#064e3b 0%,#065f46 100%);color:white;padding:24px 28px;border-radius:14px;margin-bottom:24px;display:flex;align-items:center;justify-content:space-between;">
      <div>
        <div style="font-size:22px;font-weight:800;letter-spacing:-0.5px;">🏍️ ${SHOWROOM}</div>
        <div style="font-size:11px;opacity:0.7;margin-top:4px;">${SHOWROOM_SUB}</div>
        <div style="margin-top:8px;display:inline-block;background:rgba(255,255,255,0.15);padding:3px 10px;border-radius:20px;font-size:10px;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;">
          Sale Receipt — ${s.saleType === "installment" ? "Installment" : "Cash"}
        </div>
      </div>
      <div style="text-align:right;">
        <div style="font-size:10px;opacity:0.7;">Sale Date</div>
        <div style="font-size:14px;font-weight:700;">${fmtDate(s.saleDateTime)}</div>
        <div style="font-size:10px;opacity:0.7;margin-top:6px;">Record ID</div>
        <div style="font-size:11px;font-weight:600;opacity:0.9;">${s.id || "—"}</div>
      </div>
    </div>

    ${section("🏍️ Bike Details", "#1e40af",
      row("Registration No.", s.registrationStatus === "AFR" ? "AFR" : s.registrationNo) +
      row("Company", s.bikeCompany) +
      row("Model", s.bikeModel) +
      row("Chasis No.", s.chasisNo) +
      row("Engine No.", s.engineNo)
    )}

    ${section("👤 Buyer Details", "#334155",
      row("Buyer Name", s.buyerName) +
      row("Father's Name", s.buyerFatherName) +
      row("CNIC", s.buyerCnic) +
      row("Current Address", s.buyerCurrentAddress) +
      row("Permanent Address", s.buyerPermanentAddress)
    )}

    ${section("🤝 Seller Details", "#4c1d95",
      row("Seller Name", s.salerName) +
      row("Seller Phone", s.salerNumber) +
      row("Seller CNIC", s.salerCnic) +
      row("Seller Address", s.salerAddress)
    )}

    ${section("💰 Financial Details", "#065f46",
      row("Total Sale Amount", fmt(s.totalSaleAmount), true) +
      row("Advance Received", fmt(s.advanceReceived)) +
      row("Installments Paid", fmt(s.paidInstallments)) +
      row("Balance Remaining", fmt(s.amountRemaining ?? (Number(s.totalSaleAmount || 0) - Number(s.advanceReceived || 0)))) +
      (s.saleType === "installment" ? (
        row("Installment Months", s.installmentMonths || "—") +
        row("Per Month", fmt(s.perMonthInstallment)) +
        row("Start Date", fmtDate(s.installmentStartDate)) +
        (s.installmentDescription ? row("Installment Plan Notes", s.installmentDescription) : "")
      ) : "")
    )}

    ${s.saleType === "installment" && Array.isArray(s.installments) && s.installments.length > 0 ? `
      <div style="margin-top:20px;">
        <div style="background:#0f172a;color:white;padding:8px 14px;border-radius:8px 8px 0 0;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;">
          📅 Custom Installment Schedule
        </div>
        <table style="width:100%;border-collapse:collapse;border:1px solid #e2e8f0;border-top:none;border-radius:0 0 8px 8px;overflow:hidden;font-size:11px;">
          <thead>
            <tr style="background:#f8fafc;border-bottom:1px solid #e2e8f0;text-align:left;color:#64748b;">
              <th style="padding:8px 12px;">#</th>
              <th style="padding:8px 12px;">Due Date</th>
              <th style="padding:8px 12px;">Description</th>
              <th style="padding:8px 12px;text-align:right;">Amount</th>
              <th style="padding:8px 12px;text-align:center;">Status</th>
            </tr>
          </thead>
          <tbody>
            ${s.installments.map((inst, idx) => `
              <tr style="border-bottom:1px solid #f1f5f9;">
                <td style="padding:8px 12px;font-weight:600;color:#64748b;">${inst.monthNumber || idx + 1}</td>
                <td style="padding:8px 12px;color:#1e293b;">${fmtDate(inst.dueDate)}</td>
                <td style="padding:8px 12px;color:#475569;">${inst.description || `Installment #${idx + 1}`}</td>
                <td style="padding:8px 12px;text-align:right;font-weight:700;color:#0f172a;">${fmt(inst.amount)}</td>
                <td style="padding:8px 12px;text-align:center;font-weight:700;color:${inst.paid ? "#059669" : "#d97706"}; font-size:10px;">
                  ${inst.paid ? "PAID" : "PENDING"}
                </td>
              </tr>
            `).join("")}
          </tbody>
        </table>
      </div>
    ` : ""}
  `;

  printWindow(`${SHOWROOM} — Sale Receipt`, body);
}

/* ─── INVENTORY PDF ────────────────────────────────────────── */
export function downloadInventoryPDF(inventory = [], summary = {}) {
  const rows = inventory.map((item, idx) => `
    <tr style="border-bottom:1px solid #f1f5f9;">
      <td style="padding:10px 12px;font-size:12px;color:#64748b;">${idx + 1}</td>
      <td style="padding:10px 12px;font-size:12px;font-weight:700;color:#1e293b;">${[item.bikeCompany, item.bikeModel].filter(Boolean).join(" ") || "—"}</td>
      <td style="padding:10px 12px;font-size:12px;color:#475569;">${item.registrationNo || "—"}</td>
      <td style="padding:10px 12px;font-size:12px;color:#475569;">${item.chasisNo || "—"}</td>
      <td style="padding:10px 12px;font-size:12px;color:#475569;">${item.engineNo || "—"}</td>
      <td style="padding:10px 12px;font-size:12px;font-weight:700;color:#059669;">${fmt(item.actualAmount)}</td>
      <td style="padding:10px 12px;font-size:12px;font-weight:700;color:#dc2626;">${fmt(item.amountRemaining)}</td>
      <td style="padding:10px 12px;font-size:12px;color:#475569;">${item.customerName || "—"}</td>
    </tr>
  `).join("");

  const body = `
    <!-- Header -->
    <div style="background:linear-gradient(135deg,#0f172a 0%,#1e293b 100%);color:white;padding:24px 28px;border-radius:14px;margin-bottom:24px;display:flex;align-items:center;justify-content:space-between;">
      <div>
        <div style="font-size:22px;font-weight:800;letter-spacing:-0.5px;">🏍️ ${SHOWROOM}</div>
        <div style="font-size:11px;opacity:0.7;margin-top:4px;">${SHOWROOM_SUB}</div>
        <div style="margin-top:8px;display:inline-block;background:rgba(255,255,255,0.15);padding:3px 10px;border-radius:20px;font-size:10px;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;">
          Inventory & Stock Summary Report
        </div>
      </div>
      <div style="text-align:right;">
        <div style="font-size:10px;opacity:0.7;">Report Date</div>
        <div style="font-size:14px;font-weight:700;">${new Date().toLocaleDateString("en-PK")}</div>
      </div>
    </div>

    <!-- Summary Cards -->
    <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:24px;">
      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:16px;text-align:center;">
        <div style="font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Unsold Bikes in Stock</div>
        <div style="font-size:20px;font-weight:800;color:#0f172a;margin-top:4px;">${summary.totalUnsold ?? summary.totalPurchased ?? 0}</div>
      </div>
      <div style="background:#ecfdf5;border:1px solid #a7f3d0;border-radius:10px;padding:16px;text-align:center;">
        <div style="font-size:10px;font-weight:700;color:#047857;text-transform:uppercase;">Total Inventory Value</div>
        <div style="font-size:20px;font-weight:800;color:#059669;margin-top:4px;">${fmt(summary.totalPurchaseValue)}</div>
      </div>
      <div style="background:#fff1f2;border:1px solid #fecdd3;border-radius:10px;padding:16px;text-align:center;">
        <div style="font-size:10px;font-weight:700;color:#be123c;text-transform:uppercase;">Remaining Payment</div>
        <div style="font-size:20px;font-weight:800;color:#e11d48;margin-top:4px;">${fmt(summary.remainingBalance)}</div>
      </div>
    </div>

    <!-- Table -->
    <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;color:#64748b;margin-bottom:10px;">Unsold Available Inventory List</div>
    <table style="width:100%;border-collapse:collapse;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;">
      <thead>
        <tr style="background:#f8fafc;border-bottom:1px solid #e2e8f0;">
          <th style="padding:10px 12px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">#</th>
          <th style="padding:10px 12px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Bike Model</th>
          <th style="padding:10px 12px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Reg No</th>
          <th style="padding:10px 12px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Chasis No</th>
          <th style="padding:10px 12px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Engine No</th>
          <th style="padding:10px 12px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Purchase Price</th>
          <th style="padding:10px 12px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Remaining</th>
          <th style="padding:10px 12px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Seller Name</th>
        </tr>
      </thead>
      <tbody>
        ${rows || `<tr><td colspan="8" style="text-align:center;padding:24px;color:#94a3b8;font-size:12px;">No inventory items available.</td></tr>`}
      </tbody>
    </table>
  `;

  printWindow(`${SHOWROOM} — Inventory Summary Report`, body);
}

/* ─── SALES SUMMARY PDF ────────────────────────────────────────── */
export function downloadSalesSummaryPDF(sales = [], rangeLabel = "All Time") {
  const totalSalesCount = sales.length;
  const totalRevenue = sales.reduce((sum, s) => sum + (Number(s.totalSaleAmount) || 0), 0);
  const totalAdvance = sales.reduce((sum, s) => sum + (Number(s.advanceReceived) || 0), 0);
  const totalRemaining = sales.reduce((sum, s) => sum + (Number(s.amountRemaining) || 0), 0);

  const rows = sales.map((s, idx) => `
    <tr style="border-bottom:1px solid #f1f5f9;">
      <td style="padding:8px 10px;font-size:11px;color:#64748b;">${idx + 1}</td>
      <td style="padding:8px 10px;font-size:11px;color:#1e293b;font-weight:600;">${fmtDate(s.saleDateTime || s.saleDate)}</td>
      <td style="padding:8px 10px;font-size:11px;font-weight:700;color:#1e293b;">${[s.bikeCompany, s.bikeModel].filter(Boolean).join(" ") || "—"}</td>
      <td style="padding:8px 10px;font-size:11px;color:#475569;">${s.registrationNo || "AFR"}</td>
      <td style="padding:8px 10px;font-size:11px;color:#475569;">${s.buyerName || "—"} (${s.buyerNumber || "—"})</td>
      <td style="padding:8px 10px;font-size:11px;"><span style="background:#f1f5f9;padding:2px 6px;border-radius:4px;font-size:10px;font-weight:700;text-transform:uppercase;">${s.saleType || "Cash"}</span></td>
      <td style="padding:8px 10px;font-size:11px;font-weight:700;color:#059669;text-align:right;">${fmt(s.totalSaleAmount)}</td>
      <td style="padding:8px 10px;font-size:11px;font-weight:700;color:#047857;text-align:right;">${fmt(s.advanceReceived)}</td>
      <td style="padding:8px 10px;font-size:11px;font-weight:700;color:#dc2626;text-align:right;">${fmt(s.amountRemaining)}</td>
    </tr>
  `).join("");

  const body = `
    <!-- Header -->
    <div style="background:linear-gradient(135deg,#064e3b 0%,#065f46 100%);color:white;padding:24px 28px;border-radius:14px;margin-bottom:24px;display:flex;align-items:center;justify-content:space-between;">
      <div>
        <div style="font-size:22px;font-weight:800;letter-spacing:-0.5px;">🏍️ ${SHOWROOM}</div>
        <div style="font-size:11px;opacity:0.7;margin-top:4px;">${SHOWROOM_SUB}</div>
        <div style="margin-top:8px;display:inline-block;background:rgba(255,255,255,0.15);padding:3px 10px;border-radius:20px;font-size:10px;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;">
          Sales Summary Report (${rangeLabel})
        </div>
      </div>
      <div style="text-align:right;">
        <div style="font-size:10px;opacity:0.7;">Report Date</div>
        <div style="font-size:14px;font-weight:700;">${new Date().toLocaleDateString("en-PK")}</div>
      </div>
    </div>

    <!-- Summary Cards -->
    <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:24px;">
      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:14px;text-align:center;">
        <div style="font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Bikes Sold</div>
        <div style="font-size:18px;font-weight:800;color:#0f172a;margin-top:4px;">${totalSalesCount}</div>
      </div>
      <div style="background:#ecfdf5;border:1px solid #a7f3d0;border-radius:10px;padding:14px;text-align:center;">
        <div style="font-size:10px;font-weight:700;color:#047857;text-transform:uppercase;">Total Revenue</div>
        <div style="font-size:18px;font-weight:800;color:#059669;margin-top:4px;">${fmt(totalRevenue)}</div>
      </div>
      <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:10px;padding:14px;text-align:center;">
        <div style="font-size:10px;font-weight:700;color:#15803d;text-transform:uppercase;">Advance Received</div>
        <div style="font-size:18px;font-weight:800;color:#16a34a;margin-top:4px;">${fmt(totalAdvance)}</div>
      </div>
      <div style="background:#fff1f2;border:1px solid #fecdd3;border-radius:10px;padding:14px;text-align:center;">
        <div style="font-size:10px;font-weight:700;color:#be123c;text-transform:uppercase;">Remaining Balance</div>
        <div style="font-size:18px;font-weight:800;color:#e11d48;margin-top:4px;">${fmt(totalRemaining)}</div>
      </div>
    </div>

    <!-- Table -->
    <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;color:#64748b;margin-bottom:10px;">Sales Transactions</div>
    <table style="width:100%;border-collapse:collapse;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;">
      <thead>
        <tr style="background:#f8fafc;border-bottom:1px solid #e2e8f0;">
          <th style="padding:8px 10px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">#</th>
          <th style="padding:8px 10px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Sale Date</th>
          <th style="padding:8px 10px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Bike Model</th>
          <th style="padding:8px 10px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Reg No</th>
          <th style="padding:8px 10px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Buyer Name</th>
          <th style="padding:8px 10px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Type</th>
          <th style="padding:8px 10px;text-align:right;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Sale Amount</th>
          <th style="padding:8px 10px;text-align:right;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Advance</th>
          <th style="padding:8px 10px;text-align:right;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Remaining</th>
        </tr>
      </thead>
      <tbody>
        ${rows || `<tr><td colspan="9" style="text-align:center;padding:24px;color:#94a3b8;font-size:12px;">No sales records found for this period.</td></tr>`}
      </tbody>
    </table>
  `;

  printWindow(`${SHOWROOM} — Sales Summary Report`, body);
}

/* ─── EXPENSE & FINANCIAL LEDGER PDF ────────────────────────── */
export function downloadExpensePDF(overviewData = {}, rangeLabel = "This Month") {
  const summary = overviewData.summary || {};
  const ledger = overviewData.ledger || [];
  const expenses = overviewData.expenses || [];
  const sales = overviewData.sales || [];
  const categoryBreakdown = overviewData.categoryBreakdown || [];

  const ledgerRows = ledger.map((item, idx) => `
    <tr style="border-bottom:1px solid #f1f5f9;">
      <td style="padding:7px 10px;font-size:11px;color:#64748b;">${idx + 1}</td>
      <td style="padding:7px 10px;font-size:11px;color:#334155;font-weight:600;">${item.date ? new Date(item.date).toLocaleDateString("en-PK") : "—"}</td>
      <td style="padding:7px 10px;font-size:11px;"><span style="background:#f1f5f9;padding:2px 6px;border-radius:4px;font-size:10px;font-weight:700;text-transform:uppercase;">${item.category || item.type}</span></td>
      <td style="padding:7px 10px;font-size:11px;font-weight:700;color:#1e293b;">${item.title || "—"}</td>
      <td style="padding:7px 10px;font-size:11px;font-weight:700;color:#059669;text-align:right;">${item.inflow > 0 ? `+ ${fmt(item.inflow)}` : "—"}</td>
      <td style="padding:7px 10px;font-size:11px;font-weight:700;color:#dc2626;text-align:right;">${item.outflow > 0 ? `- ${fmt(item.outflow)}` : "—"}</td>
    </tr>
  `).join("");

  const categoryRows = categoryBreakdown.map(c => `
    <tr style="border-bottom:1px solid #f1f5f9;">
      <td style="padding:6px 10px;font-size:11px;font-weight:600;color:#334155;">${c.category}</td>
      <td style="padding:6px 10px;font-size:11px;font-weight:700;color:#e11d48;text-align:right;">${fmt(c.amount)}</td>
    </tr>
  `).join("");

  const body = `
    <!-- Header -->
    <div style="background:linear-gradient(135deg,#0f172a 0%,#1e293b 100%);color:white;padding:22px 26px;border-radius:12px;margin-bottom:20px;display:flex;align-items:center;justify-content:space-between;">
      <div>
        <div style="font-size:20px;font-weight:800;letter-spacing:-0.5px;">🏍️ ${SHOWROOM}</div>
        <div style="font-size:11px;opacity:0.7;margin-top:2px;">${SHOWROOM_SUB}</div>
        <div style="margin-top:6px;display:inline-block;background:rgba(255,255,255,0.15);padding:3px 10px;border-radius:20px;font-size:10px;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;">
          Daily General Ledger & Expenses Report (${rangeLabel})
        </div>
      </div>
      <div style="text-align:right;">
        <div style="font-size:10px;opacity:0.7;">Generated On</div>
        <div style="font-size:13px;font-weight:700;">${new Date().toLocaleDateString("en-PK")}</div>
      </div>
    </div>

    <!-- Summary Metrics -->
    <div style="display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:22px;">
      <div style="background:${(summary.netCashFlow || 0) >= 0 ? "#f0fdf4" : "#fff1f2"};border:1px solid ${(summary.netCashFlow || 0) >= 0 ? "#bbf7d0" : "#fecdd3"};border-radius:8px;padding:10px;text-align:center;">
        <div style="font-size:8px;font-weight:700;color:#475569;text-transform:uppercase;">Day-End Cash Balance</div>
        <div style="font-size:15px;font-weight:800;color:${(summary.netCashFlow || 0) >= 0 ? "#15803d" : "#be123c"};margin-top:3px;">${fmt(summary.netCashFlow)}</div>
      </div>
      <div style="background:#fff1f2;border:1px solid #fecdd3;border-radius:8px;padding:10px;text-align:center;">
        <div style="font-size:8px;font-weight:700;color:#9f1239;text-transform:uppercase;">Bikes Purchased (Outflow)</div>
        <div style="font-size:15px;font-weight:800;color:#be123c;margin-top:3px;">-${fmt(summary.totalBikePurchasesCost)}</div>
      </div>
      <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:10px;text-align:center;">
        <div style="font-size:8px;font-weight:700;color:#166534;text-transform:uppercase;">Bikes Sold (Inflow)</div>
        <div style="font-size:15px;font-weight:800;color:#15803d;margin-top:3px;">+${fmt(summary.totalBikeSalesRevenue)}</div>
      </div>
      <div style="background:#fff1f2;border:1px solid #fecdd3;border-radius:8px;padding:10px;text-align:center;">
        <div style="font-size:8px;font-weight:700;color:#9f1239;text-transform:uppercase;">General Expenses</div>
        <div style="font-size:15px;font-weight:800;color:#be123c;margin-top:3px;">-${fmt(summary.totalGeneralExpenses)}</div>
      </div>
      <div style="background:#f0fdfa;border:1px solid #99f6e4;border-radius:8px;padding:10px;text-align:center;">
        <div style="font-size:8px;font-weight:700;color:#115e59;text-transform:uppercase;">Net Showroom Profit</div>
        <div style="font-size:15px;font-weight:800;color:#0f766e;margin-top:3px;">${fmt(summary.netProfit)}</div>
      </div>
    </div>

    <!-- Category Breakdown Table -->
    ${categoryBreakdown.length > 0 ? `
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;color:#64748b;margin-bottom:8px;">Expense Breakdown by Category</div>
      <table style="width:100%;max-width:400px;border-collapse:collapse;border:1px solid #e2e8f0;border-radius:6px;overflow:hidden;margin-bottom:22px;">
        <thead>
          <tr style="background:#f8fafc;border-bottom:1px solid #e2e8f0;">
            <th style="padding:6px 10px;text-align:left;font-size:9px;font-weight:700;color:#64748b;text-transform:uppercase;">Category</th>
            <th style="padding:6px 10px;text-align:right;font-size:9px;font-weight:700;color:#64748b;text-transform:uppercase;">Total Amount</th>
          </tr>
        </thead>
        <tbody>
          ${categoryRows}
        </tbody>
      </table>
    ` : ""}

    <!-- Daily General Ledger Table -->
    <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;color:#64748b;margin-bottom:8px;">Daily General Ledger Feed (${ledger.length} Entries)</div>
    <table style="width:100%;border-collapse:collapse;border:1px solid #e2e8f0;border-radius:6px;overflow:hidden;margin-bottom:24px;">
      <thead>
        <tr style="background:#f8fafc;border-bottom:1px solid #e2e8f0;">
          <th style="padding:8px 10px;text-align:left;font-size:9px;font-weight:700;color:#64748b;text-transform:uppercase;">#</th>
          <th style="padding:8px 10px;text-align:left;font-size:9px;font-weight:700;color:#64748b;text-transform:uppercase;">Date</th>
          <th style="padding:8px 10px;text-align:left;font-size:9px;font-weight:700;color:#64748b;text-transform:uppercase;">Type</th>
          <th style="padding:8px 10px;text-align:left;font-size:9px;font-weight:700;color:#64748b;text-transform:uppercase;">Transaction Details</th>
          <th style="padding:8px 10px;text-align:right;font-size:9px;font-weight:700;color:#64748b;text-transform:uppercase;">Inflow (+)</th>
          <th style="padding:8px 10px;text-align:right;font-size:9px;font-weight:700;color:#64748b;text-transform:uppercase;">Outflow (-)</th>
        </tr>
      </thead>
      <tbody>
        ${ledgerRows || `<tr><td colspan="6" style="text-align:center;padding:16px;color:#94a3b8;font-size:11px;">No ledger activity recorded in this period.</td></tr>`}
      </tbody>
      <tfoot>
        <tr style="background:#0f172a;color:white;font-weight:700;font-size:11px;">
          <td colspan="4" style="padding:8px 10px;text-transform:uppercase;">Total Day-End Closing Balance</td>
          <td style="padding:8px 10px;text-align:right;color:#4ade80;">+ ${fmt(summary.totalInflow)}</td>
          <td style="padding:8px 10px;text-align:right;color:#f87171;">- ${fmt(summary.totalOutflow)}</td>
        </tr>
      </tfoot>
    </table>
  `;

  printWindow(`${SHOWROOM} — Daily General Ledger Report (${rangeLabel})`, body);
}

export function downloadNetIncomePDF({
  rangeLabel = "Daily Summary",
  date = new Date().toLocaleDateString("en-PK"),
  grossProfit = 0,
  deductibleExpenses = 0,
  neglectedExpenses = 0,
  netIncome = 0,
  expensesList = [],
}) {
  const expenseRows = expensesList.map((exp, idx) => `
    <tr style="border-bottom:1px solid #f1f5f9;">
      <td style="padding:8px 10px;font-size:11px;color:#64748b;">${idx + 1}</td>
      <td style="padding:8px 10px;font-size:11px;font-weight:600;color:#1e293b;">${exp.title || "—"}</td>
      <td style="padding:8px 10px;font-size:11px;color:#64748b;">${exp.category || "General"}</td>
      <td style="padding:8px 10px;font-size:11px;color:#475569;">${exp.description || "—"}</td>
      <td style="padding:8px 10px;font-size:11px;font-weight:700;text-align:right;color:#e11d48;">Rs. ${Number(exp.amount || 0).toLocaleString()}</td>
      <td style="padding:8px 10px;font-size:10px;font-weight:700;text-align:center;">
        <span style="padding:2px 8px;border-radius:12px;${exp.deductFromProfit ? "background:#fee2e2;color:#991b1b;" : "background:#f1f5f9;color:#64748b;"}">
          ${exp.deductFromProfit ? "Deducted" : "Neglected"}
        </span>
      </td>
    </tr>
  `).join("");

  const body = `
    <div style="border-bottom:2px solid #0f172a;padding-bottom:14px;margin-bottom:20px;display:flex;justify-content:space-between;align-items:flex-end;">
      <div>
        <h1 style="font-size:22px;font-weight:900;color:#0f172a;letter-spacing:-0.02em;">${SHOWROOM}</h1>
        <p style="font-size:11px;color:#64748b;font-weight:500;margin-top:2px;">${SHOWROOM_SUB}</p>
      </div>
      <div style="text-align:right;">
        <h2 style="font-size:13px;font-weight:800;color:#059669;text-transform:uppercase;letter-spacing:0.04em;">Daily Net Income Report</h2>
        <p style="font-size:11px;color:#64748b;margin-top:2px;">${rangeLabel} (${date})</p>
      </div>
    </div>

    <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:16px;margin-bottom:24px;">
      <div style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:12px;text-align:center;">
        <div style="background:#ecfdf5;border:1px solid #a7f3d0;border-radius:8px;padding:12px;">
          <div style="font-size:9px;font-weight:700;color:#047857;text-transform:uppercase;">Bike Sale Gross Profit</div>
          <div style="font-size:16px;font-weight:800;color:#059669;margin-top:4px;">Rs. ${Number(grossProfit).toLocaleString()}</div>
        </div>
        <div style="background:#fff1f2;border:1px solid #fecdd3;border-radius:8px;padding:12px;">
          <div style="font-size:9px;font-weight:700;color:#be123c;text-transform:uppercase;">Deductible Expenses</div>
          <div style="font-size:16px;font-weight:800;color:#e11d48;margin-top:4px;">-Rs. ${Number(deductibleExpenses).toLocaleString()}</div>
        </div>
        <div style="background:#f8fafc;border:1px solid #cbd5e1;border-radius:8px;padding:12px;">
          <div style="font-size:9px;font-weight:700;color:#475569;text-transform:uppercase;">Neglected Expenses</div>
          <div style="font-size:16px;font-weight:800;color:#64748b;margin-top:4px;">Rs. ${Number(neglectedExpenses).toLocaleString()}</div>
        </div>
        <div style="background:#f0fdf4;border:1px solid #86efac;border-radius:8px;padding:12px;">
          <div style="font-size:9px;font-weight:700;color:#15803d;text-transform:uppercase;">Final Net Income</div>
          <div style="font-size:16px;font-weight:800;color:#16a34a;margin-top:4px;">Rs. ${Number(netIncome).toLocaleString()}</div>
        </div>
      </div>
    </div>

    <div style="font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:0.05em;color:#475569;margin-bottom:10px;">Itemized Expenses & Deduction Breakdown</div>
    <table style="width:100%;border-collapse:collapse;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;margin-bottom:24px;">
      <thead>
        <tr style="background:#f1f5f9;border-bottom:1px solid #e2e8f0;">
          <th style="padding:8px 10px;text-align:left;font-size:9px;font-weight:700;color:#64748b;text-transform:uppercase;">#</th>
          <th style="padding:8px 10px;text-align:left;font-size:9px;font-weight:700;color:#64748b;text-transform:uppercase;">Expense Title</th>
          <th style="padding:8px 10px;text-align:left;font-size:9px;font-weight:700;color:#64748b;text-transform:uppercase;">Category</th>
          <th style="padding:8px 10px;text-align:left;font-size:9px;font-weight:700;color:#64748b;text-transform:uppercase;">Description</th>
          <th style="padding:8px 10px;text-align:right;font-size:9px;font-weight:700;color:#64748b;text-transform:uppercase;">Amount</th>
          <th style="padding:8px 10px;text-align:center;font-size:9px;font-weight:700;color:#64748b;text-transform:uppercase;">Profit Status</th>
        </tr>
      </thead>
      <tbody>
        ${expenseRows || `<tr><td colspan="6" style="text-align:center;padding:16px;color:#94a3b8;font-size:11px;">No expenses recorded for this period.</td></tr>`}
      </tbody>
    </table>
  `;

  printWindow(`${SHOWROOM} — Net Income Report (${date})`, body);
}

/* ─── EARNING & PROFIT ANALYTICS PDF ────────────────────────── */
export function downloadEarningPDF(earningData = {}, rangeLabel = "All Time") {
  const summary = earningData.summary || {};
  const profitList = earningData.profitList || [];

  const rows = profitList.map((item, idx) => `
    <tr style="border-bottom:1px solid #f1f5f9;">
      <td style="padding:8px 10px;font-size:11px;color:#64748b;">${idx + 1}</td>
      <td style="padding:8px 10px;font-size:11px;color:#1e293b;font-weight:600;">${item.date ? new Date(item.date).toLocaleDateString("en-PK") : "—"}</td>
      <td style="padding:8px 10px;font-size:11px;">
        <span style="padding:2px 8px;border-radius:12px;font-size:9px;font-weight:700;text-transform:uppercase;${item.recordType === "sale" ? "background:#dbeafe;color:#1e40af;" : "background:#f3e8ff;color:#6b21a8;"}">
          ${item.recordType === "sale" ? "Bike Sale" : "Registration"}
        </span>
      </td>
      <td style="padding:8px 10px;font-size:11px;font-weight:700;color:#1e293b;">
        ${[item.bikeCompany, item.bikeModel].filter(Boolean).join(" ") || item.title || "—"}
        <div style="font-size:10px;font-weight:500;color:#64748b;">${item.registrationNo || item.chasisNo || ""}</div>
      </td>
      <td style="padding:8px 10px;font-size:11px;color:#475569;">${item.buyerName || item.customerName || "—"}</td>
      <td style="padding:8px 10px;font-size:11px;font-weight:700;color:#059669;text-align:right;">${fmt(item.saleAmount || item.revenue)}</td>
      <td style="padding:8px 10px;font-size:11px;font-weight:600;color:#64748b;text-align:right;">${fmt(item.purchaseCost || item.cost)}</td>
      <td style="padding:8px 10px;font-size:11px;font-weight:800;color:${(item.profit || 0) >= 0 ? "#047857" : "#be123c"};text-align:right;">${fmt(item.profit)}</td>
    </tr>
  `).join("");

  const body = `
    <!-- Header -->
    <div style="background:linear-gradient(135deg,#0f172a 0%,#1e293b 100%);color:white;padding:24px 28px;border-radius:14px;margin-bottom:22px;display:flex;align-items:center;justify-content:space-between;">
      <div>
        <div style="font-size:22px;font-weight:800;letter-spacing:-0.5px;">🏍️ ${SHOWROOM}</div>
        <div style="font-size:11px;opacity:0.7;margin-top:4px;">${SHOWROOM_SUB}</div>
        <div style="margin-top:8px;display:inline-block;background:rgba(255,255,255,0.15);padding:3px 10px;border-radius:20px;font-size:10px;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;">
          Earning & Profit Analytics Report (${rangeLabel})
        </div>
      </div>
      <div style="text-align:right;">
        <div style="font-size:10px;opacity:0.7;">Report Date</div>
        <div style="font-size:14px;font-weight:700;">${new Date().toLocaleDateString("en-PK")}</div>
      </div>
    </div>

    <!-- Summary Metrics -->
    <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:16px;">
      <div style="background:#ecfdf5;border:1px solid #a7f3d0;border-radius:10px;padding:14px;text-align:center;">
        <div style="font-size:10px;font-weight:700;color:#047857;text-transform:uppercase;">Total Net Profit</div>
        <div style="font-size:20px;font-weight:800;color:#059669;margin-top:4px;">${fmt(summary.totalProfit)}</div>
      </div>
      <div style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:10px;padding:14px;text-align:center;">
        <div style="font-size:10px;font-weight:700;color:#1e40af;text-transform:uppercase;">Bike Sales Margin</div>
        <div style="font-size:18px;font-weight:800;color:#2563eb;margin-top:4px;">${fmt(summary.totalBikeSalesProfit)}</div>
      </div>
      <div style="background:#faf5ff;border:1px solid #e9d5ff;border-radius:10px;padding:14px;text-align:center;">
        <div style="font-size:10px;font-weight:700;color:#6b21a8;text-transform:uppercase;">Registration Margin</div>
        <div style="font-size:18px;font-weight:800;color:#7e22ce;margin-top:4px;">${fmt(summary.totalRegProfit)}</div>
      </div>
    </div>

    <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:24px;">
      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:12px;text-align:center;">
        <div style="font-size:9px;font-weight:700;color:#64748b;text-transform:uppercase;">Sales Revenue (${summary.totalSalesCount || 0} Bikes)</div>
        <div style="font-size:15px;font-weight:800;color:#0f172a;margin-top:3px;">${fmt(summary.totalSalesRevenue)}</div>
      </div>
      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:12px;text-align:center;">
        <div style="font-size:9px;font-weight:700;color:#64748b;text-transform:uppercase;">Purchases Cost (${summary.totalPurchasesCount || 0} Bikes)</div>
        <div style="font-size:15px;font-weight:800;color:#0f172a;margin-top:3px;">${fmt(summary.totalPurchasesCost)}</div>
      </div>
      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:12px;text-align:center;">
        <div style="font-size:9px;font-weight:700;color:#64748b;text-transform:uppercase;">Stock Value (${summary.currentStockCount || 0} Bikes Unsold)</div>
        <div style="font-size:15px;font-weight:800;color:#0f172a;margin-top:3px;">${fmt(summary.currentStockValue)}</div>
      </div>
    </div>

    <!-- Table -->
    <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;color:#64748b;margin-bottom:10px;">Itemized Profit & Earnings Ledger (${profitList.length} Transactions)</div>
    <table style="width:100%;border-collapse:collapse;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;">
      <thead>
        <tr style="background:#f8fafc;border-bottom:1px solid #e2e8f0;">
          <th style="padding:8px 10px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">#</th>
          <th style="padding:8px 10px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Date</th>
          <th style="padding:8px 10px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Type</th>
          <th style="padding:8px 10px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Bike / Service</th>
          <th style="padding:8px 10px;text-align:left;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Customer</th>
          <th style="padding:8px 10px;text-align:right;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Revenue</th>
          <th style="padding:8px 10px;text-align:right;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Cost</th>
          <th style="padding:8px 10px;text-align:right;font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;">Profit</th>
        </tr>
      </thead>
      <tbody>
        ${rows || `<tr><td colspan="8" style="text-align:center;padding:24px;color:#94a3b8;font-size:12px;">No profit records found for this period.</td></tr>`}
      </tbody>
      <tfoot>
        <tr style="background:#0f172a;color:white;font-weight:700;font-size:11px;">
          <td colspan="7" style="padding:10px;text-transform:uppercase;">Total Net Profit for Period</td>
          <td style="padding:10px;text-align:right;color:#4ade80;font-size:13px;">${fmt(summary.totalProfit)}</td>
        </tr>
      </tfoot>
    </table>
  `;

  printWindow(`${SHOWROOM} — Earning & Profit Report (${rangeLabel})`, body);
}
