"use client";

export const dynamic = "force-dynamic";

import { useState, useEffect, useMemo } from "react";
import { ArrowLeft, Check, Plus, Loader2, RefreshCw, Search, FileDown, X, ClipboardList, Pencil, Trash2, User, Building2, Eye } from "lucide-react";
import { useRouter } from "next/navigation";
import MobileBottomNav from "@/app/components/MobileBottomNav";
import Footer from "@/app/components/Footer";

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;

function money(n) { return `Rs. ${Number(n || 0).toLocaleString()}`; }
function fmtDate(v) {
  if (!v) return "—";
  const d = v?.seconds ? new Date(v.seconds * 1000) : new Date(v);
  if (isNaN(d)) return "—";
  return d.toLocaleDateString("en-PK") + " " + d.toLocaleTimeString("en-PK", { hour: "2-digit", minute: "2-digit" });
}

function downloadRegPDF(item) {
  const win = window.open("", "_blank", "width=860,height=700");
  const profit = Number(item.customerTotalMoney || 0) - Number(item.agentTotalMoney || 0);
  const isExternal = item.registrationType === "external" || !item.bikeId;

  const rows = [
    ["Registration Type", isExternal ? "👤 3rd Party Customer Bike" : "🏢 Showroom Purchased Bike"],
    ...(isExternal && item.customerName ? [["Customer / Owner Name", item.customerName]] : []),
    ...(isExternal && item.customerPhone ? [["Customer Contact", item.customerPhone]] : []),
    ["Bike Company", item.bikeCompany],
    ["Bike Model", item.bikeModel],
    ["Chasis No", item.chasisNo || "—"],
    ...(isExternal && item.engineNo ? [["Engine No", item.engineNo]] : []),
    ["Registration No", item.registrationNo || "AFR"],
    ["Agent / Letter", item.agentLetter],
    ["Agent Fee (Cost)", money(item.agentTotalMoney)],
    ["Customer Fee (Charged)", money(item.customerTotalMoney)],
    ["Showroom Profit", money(profit)],
    ["Agent Advance Paid", money(item.agentAdvance)],
    ["Description", item.description || "—"],
    ["Submitted Date", fmtDate(item.createdAt)],
  ];

  win.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8"/>
  <title>Registration — ${item.bikeCompany} ${item.bikeModel}</title>
  <style>*{box-sizing:border-box;margin:0;padding:0;font-family:'Segoe UI',Arial,sans-serif;}
  body{background:#fff;padding:28px;color:#1e293b;}
  @media print{.no-print{display:none!important;}}</style></head><body>
  <div class="no-print" style="text-align:right;margin-bottom:16px;">
    <button onclick="window.print()" style="padding:8px 20px;background:#0f172a;color:white;border:none;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;">🖨️ Print / Save PDF</button>
  </div>
  <div style="background:linear-gradient(135deg,#0f172a,#1e3a5f);color:white;padding:24px 28px;border-radius:14px;margin-bottom:22px;display:flex;justify-content:space-between;align-items:center;">
    <div>
      <div style="font-size:22px;font-weight:800;">🏍️ Ammar Autos</div>
      <div style="font-size:11px;opacity:.7;margin-top:4px;">Bike Showroom Management</div>
      <div style="margin-top:8px;display:inline-block;background:rgba(255,255,255,.15);padding:3px 10px;border-radius:20px;font-size:10px;font-weight:700;text-transform:uppercase;">
        ${isExternal ? "3rd Party Registration" : "Showroom Bike Registration"}
      </div>
    </div>
    <div style="text-align:right;">
      <div style="font-size:10px;opacity:.7;">Status</div>
      <div style="font-size:14px;font-weight:700;">${item.paperReceived ? "✅ Paper Received" : "⏳ Pending"}</div>
    </div>
  </div>
  <table style="width:100%;border-collapse:collapse;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;">
    ${rows.map(([l, v]) => `<tr style="border-bottom:1px solid #f1f5f9;">
      <td style="padding:10px 14px;font-size:12px;color:#64748b;font-weight:600;width:40%;">${l}</td>
      <td style="padding:10px 14px;font-size:12px;color:#1e293b;font-weight:500;">${v || "—"}</td>
    </tr>`).join("")}
  </table>
  <div style="margin-top:24px;padding-top:12px;border-top:1px solid #e2e8f0;text-align:center;font-size:11px;color:#94a3b8;">
    Generated by Ammar Autos — ${new Date().toLocaleDateString("en-PK", { year: "numeric", month: "long", day: "numeric" })}
  </div>
</body></html>`);
  win.document.close();
}

const emptyForm = {
  registrationType: "showroom",
  searchType: "chasisNo",
  searchValue: "",
  customerName: "",
  customerPhone: "",
  bikeCompany: "",
  bikeModel: "",
  chasisNo: "",
  engineNo: "",
  registrationNo: "",
  registrationDateTime: "",
  agentLetter: "",
  agentTotalMoney: "",
  customerTotalMoney: "",
  agentAdvance: "",
  description: "",
};

export default function RegistrationPage() {
  const router = useRouter();
  const [registrations, setRegistrations] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [form, setForm] = useState(emptyForm);
  const [editingId, setEditingId] = useState(null);
  const [isViewOnly, setIsViewOnly] = useState(false);
  const [existingBike, setExistingBike] = useState(null);
  const [searching, setSearching] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [formError, setFormError] = useState("");

  const fetchRegistrations = async () => {
    setLoading(true);
    try {
      const res = await fetch(`${BASE_URL}/registration`);
      const data = await res.json();
      if (res.ok) setRegistrations(data.data || []);
    } catch (e) { console.error(e); }
    finally { setLoading(false); }
  };

  useEffect(() => { fetchRegistrations(); }, []);

  const filtered = useMemo(() => {
    if (!search.trim()) return registrations;
    const q = search.toLowerCase().trim();
    return registrations.filter(r =>
      r.bikeCompany?.toLowerCase().includes(q) ||
      r.bikeModel?.toLowerCase().includes(q) ||
      r.chasisNo?.toLowerCase().includes(q) ||
      r.registrationNo?.toLowerCase().includes(q) ||
      r.agentLetter?.toLowerCase().includes(q) ||
      r.customerName?.toLowerCase().includes(q) ||
      r.customerPhone?.toLowerCase().includes(q)
    );
  }, [registrations, search]);

  useEffect(() => {
    if (showForm) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "";
    }
    return () => {
      document.body.style.overflow = "";
    };
  }, [showForm]);

  const handleSearchBike = async () => {
    if (!form.searchValue.trim() || isViewOnly) return;
    setSearching(true);
    setExistingBike(null);
    setFormError("");
    try {
      const res = await fetch(`${BASE_URL}/registration/search-bike?searchType=${form.searchType}&searchValue=${encodeURIComponent(form.searchValue.trim())}`);
      const data = await res.json();
      if (data.found) {
        setExistingBike(data.data);
        setForm(f => ({ ...f, registrationNo: data.data.registrationNo || f.registrationNo }));
      } else {
        setFormError(`No purchase found with ${form.searchType === "chasisNo" ? "Chasis No" : "Reg No"}: "${form.searchValue}"`);
      }
    } catch (e) {
      setFormError("Search failed. Please try again.");
    } finally {
      setSearching(false);
    }
  };

  const handleOpenEdit = (item) => {
    const isExt = item.registrationType === "external" || !item.bikeId;
    setEditingId(item.id);
    setIsViewOnly(false);
    if (!isExt) {
      setExistingBike({
        id: item.bikeId,
        bikeCompany: item.bikeCompany,
        bikeModel: item.bikeModel,
        chasisNo: item.chasisNo,
        registrationNo: item.registrationNo
      });
    } else {
      setExistingBike(null);
    }
    setForm({
      registrationType: isExt ? "external" : "showroom",
      searchType: item.searchType || "chasisNo",
      searchValue: item.searchValue || item.chasisNo || "",
      customerName: item.customerName || "",
      customerPhone: item.customerPhone || "",
      bikeCompany: item.bikeCompany || "",
      bikeModel: item.bikeModel || "",
      chasisNo: item.chasisNo || "",
      engineNo: item.engineNo || "",
      registrationNo: item.registrationNo || "",
      registrationDateTime: item.registrationDateTime ? new Date(item.registrationDateTime).toISOString().slice(0, 16) : "",
      agentLetter: item.agentLetter || "",
      agentTotalMoney: item.agentTotalMoney ?? "",
      customerTotalMoney: item.customerTotalMoney ?? "",
      agentAdvance: item.agentAdvance ?? "",
      description: item.description || "",
    });
    setFormError("");
    setShowForm(true);
  };

  const handleOpenView = (item) => {
    handleOpenEdit(item);
    setIsViewOnly(true);
  };

  const handleDelete = async (id) => {
    if (!window.confirm("Are you sure you want to delete this registration record?")) return;
    try {
      const res = await fetch(`${BASE_URL}/registration/${id}`, { method: "DELETE" });
      if (res.ok) {
        fetchRegistrations();
      } else {
        const d = await res.json();
        alert(d.message || "Failed to delete registration");
      }
    } catch (e) {
      alert("Delete failed. Please try again.");
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (isViewOnly) return;
    setSubmitting(true);
    setFormError("");
    try {
      let payload = {};
      if (form.registrationType === "showroom") {
        if (!existingBike) {
          setFormError("Please search and link a showroom purchased bike first.");
          setSubmitting(false);
          return;
        }
        payload = {
          registrationType: "showroom",
          searchType: form.searchType,
          searchValue: form.searchValue,
          bikeId: existingBike.id,
          bikeCompany: existingBike.bikeCompany || "",
          bikeModel: existingBike.bikeModel || "",
          chasisNo: existingBike.chasisNo || "",
          registrationNo: form.registrationNo || existingBike.registrationNo || "",
          registrationDateTime: form.registrationDateTime || new Date().toISOString(),
          agentLetter: form.agentLetter,
          agentTotalMoney: form.agentTotalMoney,
          customerTotalMoney: form.customerTotalMoney,
          agentAdvance: form.agentAdvance,
          description: form.description,
        };
      } else {
        if (!form.bikeCompany.trim() || !form.bikeModel.trim()) {
          setFormError("Bike company and model are required for 3rd party registration.");
          setSubmitting(false);
          return;
        }
        payload = {
          registrationType: "external",
          customerName: form.customerName,
          customerPhone: form.customerPhone,
          bikeCompany: form.bikeCompany,
          bikeModel: form.bikeModel,
          chasisNo: form.chasisNo,
          engineNo: form.engineNo,
          registrationNo: form.registrationNo || "",
          registrationDateTime: form.registrationDateTime || new Date().toISOString(),
          agentLetter: form.agentLetter,
          agentTotalMoney: form.agentTotalMoney,
          customerTotalMoney: form.customerTotalMoney,
          agentAdvance: form.agentAdvance,
          description: form.description,
        };
      }

      const url = editingId ? `${BASE_URL}/registration/${editingId}` : `${BASE_URL}/registration`;
      const method = editingId ? "PUT" : "POST";

      const res = await fetch(url, {
        method,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      if (res.ok) {
        setForm(emptyForm);
        setEditingId(null);
        setIsViewOnly(false);
        setExistingBike(null);
        setShowForm(false);
        fetchRegistrations();
      } else {
        const d = await res.json();
        setFormError(d.message || "Failed to save registration");
      }
    } catch (e) {
      setFormError("Save failed. Please try again.");
    } finally {
      setSubmitting(false);
    }
  };

  const handleTogglePaper = async (id) => {
    try {
      const res = await fetch(`${BASE_URL}/registration/${id}/receive-paper`, { method: "PATCH" });
      if (res.ok) {
        fetchRegistrations();
      } else {
        alert("Failed to update status");
      }
    } catch (e) { alert("Update failed"); }
  };

  const pending = registrations.filter(r => !r.paperReceived).length;
  const received = registrations.filter(r => r.paperReceived).length;
  const totalRegProfit = registrations.reduce((sum, r) => sum + (Number(r.customerTotalMoney || 0) - Number(r.agentTotalMoney || 0)), 0);

  const canSubmit = form.registrationType === "showroom" ? Boolean(existingBike) : Boolean(form.bikeCompany.trim() && form.bikeModel.trim());

  return (
    <div className="min-h-screen bg-slate-50/50 text-slate-900 font-sans antialiased">
      {/* Header */}
      <header className="w-full bg-white border-b border-slate-200 sticky top-0 z-40 shadow-sm backdrop-blur-md">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="bg-slate-900 text-white p-2.5 rounded-xl shadow-md">
              <ClipboardList size={20} />
            </div>
            <div>
              <h1 className="text-xl font-bold tracking-tight text-slate-900">Ammar Autos</h1>
              <p className="text-xs text-slate-500 font-medium -mt-0.5">Registration Management</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <button onClick={fetchRegistrations} className="p-2 text-slate-400 hover:text-slate-900 hover:bg-slate-100 rounded-xl transition-colors"><RefreshCw size={16} /></button>
            <button
              onClick={() => { setShowForm(true); setEditingId(null); setIsViewOnly(false); setForm(emptyForm); setExistingBike(null); setFormError(""); }}
              className="flex items-center gap-2 bg-slate-900 text-white text-sm font-semibold px-4 py-2.5 rounded-xl hover:bg-slate-700 transition-all shadow-md"
            >
              <Plus size={16} /> Add Registration
            </button>
            <button onClick={() => router.push("/dashboard")} className="flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-900 transition-colors">
              <ArrowLeft size={16} /> Back
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-6 py-8 space-y-6">

        {/* Stats Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
          {[
            { label: "Total Registrations", value: registrations.length, color: "slate" },
            { label: "Pending Papers", value: pending, color: "rose" },
            { label: "Completed Papers", value: received, color: "emerald" },
            { label: "Registration Profit", value: money(totalRegProfit), color: "teal" },
          ].map(s => (
            <div key={s.label} className="bg-white rounded-2xl border border-slate-200 shadow-sm p-5 text-center">
              <p className="text-xs font-bold uppercase tracking-wider text-slate-400">{s.label}</p>
              <p className={`text-2xl font-black mt-1 text-${s.color}-600`}>{s.value}</p>
            </div>
          ))}
        </div>

        {/* Search Bar */}
        <div className="flex items-center gap-3 bg-white p-4 rounded-2xl border border-slate-200 shadow-sm">
          <Search size={18} className="text-slate-400" />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search by bike, customer, chasis no, registration no, agent..."
            className="w-full text-sm bg-transparent outline-none"
          />
          {search && <button onClick={() => setSearch("")} className="text-slate-300 hover:text-slate-500"><X size={16} /></button>}
        </div>

        {/* Registration Table */}
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between">
            <h2 className="text-sm font-bold uppercase tracking-wider text-slate-500">Registration Records ({filtered.length})</h2>
          </div>
          {loading ? (
            <div className="flex justify-center py-16"><Loader2 size={28} className="animate-spin text-slate-400" /></div>
          ) : filtered.length === 0 ? (
            <div className="py-16 text-center">
              <ClipboardList size={40} className="mx-auto text-slate-300 mb-3" />
              <p className="text-sm text-slate-400 font-semibold">No registration records found.</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-slate-50 border-b border-slate-200">
                    {["#", "Type", "Bike & Owner", "Chasis No", "Reg No", "Agent", "Agent Fee", "Customer Fee", "Profit", "Advance", "Date", "Status", "Actions"].map(h => (
                      <th key={h} className="text-left px-4 py-3 text-xs font-bold uppercase tracking-wider text-slate-500 whitespace-nowrap">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {filtered.map((item, i) => {
                    const profit = Number(item.customerTotalMoney || 0) - Number(item.agentTotalMoney || 0);
                    const isExternal = item.registrationType === "external" || !item.bikeId;
                    return (
                      <tr key={item.id} className={`border-b border-slate-100 transition-colors ${!item.paperReceived ? "bg-rose-50/40 hover:bg-rose-50" : "hover:bg-slate-50"}`}>
                        <td className="px-4 py-3 text-slate-400 font-medium">{i + 1}</td>
                        <td className="px-4 py-3 whitespace-nowrap">
                          <span className={`px-2 py-0.5 rounded-full text-[11px] font-bold ${isExternal ? "bg-amber-100 text-amber-800 border border-amber-200" : "bg-blue-100 text-blue-800 border border-blue-200"}`}>
                            {isExternal ? "3rd Party" : "Showroom"}
                          </span>
                        </td>
                        <td className="px-4 py-3 whitespace-nowrap">
                          <div className="font-semibold text-slate-800">{item.bikeCompany} {item.bikeModel}</div>
                          {item.customerName && (
                            <div className="text-xs text-slate-500 flex items-center gap-1 mt-0.5">
                              <User size={11} className="text-slate-400" />
                              <span>{item.customerName}</span>
                              {item.customerPhone && <span className="text-slate-400">({item.customerPhone})</span>}
                            </div>
                          )}
                        </td>
                        <td className="px-4 py-3 text-slate-600 whitespace-nowrap">{item.chasisNo || "—"}</td>
                        <td className="px-4 py-3 font-mono text-slate-700 whitespace-nowrap">{item.registrationNo || "AFR"}</td>
                        <td className="px-4 py-3 text-slate-600 whitespace-nowrap">{item.agentLetter || "—"}</td>
                        <td className="px-4 py-3 font-semibold text-rose-700 whitespace-nowrap">{money(item.agentTotalMoney)}</td>
                        <td className="px-4 py-3 font-semibold text-slate-900 whitespace-nowrap">{money(item.customerTotalMoney)}</td>
                        <td className="px-4 py-3 whitespace-nowrap">
                          <span className={`px-2 py-0.5 rounded-full text-xs font-bold ${profit >= 0 ? "bg-emerald-100 text-emerald-800" : "bg-rose-100 text-rose-800"}`}>
                            {profit >= 0 ? "+" : ""}{money(profit)}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-slate-600 whitespace-nowrap">{money(item.agentAdvance)}</td>
                        <td className="px-4 py-3 text-slate-500 whitespace-nowrap">{fmtDate(item.createdAt)}</td>
                        <td className="px-4 py-3 whitespace-nowrap">
                          <span className={`px-2.5 py-1 rounded-full text-xs font-bold ${item.paperReceived ? "bg-emerald-100 text-emerald-700" : "bg-rose-100 text-rose-700"}`}>
                            {item.paperReceived ? "Received" : "Pending"}
                          </span>
                        </td>
                        <td className="px-4 py-3 whitespace-nowrap">
                          <div className="flex items-center gap-1">
                            <button
                              onClick={() => handleTogglePaper(item.id)}
                              className={`p-1.5 rounded-lg transition-all ${item.paperReceived ? "text-emerald-600 hover:bg-emerald-50" : "text-rose-500 hover:bg-rose-50"}`}
                              title={item.paperReceived ? "Mark as Pending" : "Approve / Paper Received"}
                            >
                              <Check size={15} />
                            </button>
                            <button
                              onClick={() => handleOpenView(item)}
                              className="p-1.5 text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-all"
                              title="View Registration Details"
                            >
                              <Eye size={15} />
                            </button>
                            <button
                              onClick={() => handleOpenEdit(item)}
                              className="p-1.5 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-all"
                              title="Edit Registration"
                            >
                              <Pencil size={15} />
                            </button>
                            <button
                              onClick={() => handleDelete(item.id)}
                              className="p-1.5 text-slate-400 hover:text-rose-600 hover:bg-rose-50 rounded-lg transition-all"
                              title="Delete Registration"
                            >
                              <Trash2 size={15} />
                            </button>
                            <button
                              onClick={() => downloadRegPDF(item)}
                              className="p-1.5 text-slate-400 hover:text-emerald-600 hover:bg-emerald-50 rounded-lg transition-all"
                              title="Download PDF"
                            >
                              <FileDown size={15} />
                            </button>
                          </div>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </main>

      <Footer />
      <MobileBottomNav />

      {/* Add / Edit / View Registration Modal */}
      {showForm && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between px-6 py-5 border-b border-slate-200">
              <h2 className="text-lg font-bold text-slate-900">
                {isViewOnly ? "View Registration Record" : (editingId ? "Edit Registration" : "Add Registration")}
              </h2>
              <button onClick={() => { setShowForm(false); setEditingId(null); setIsViewOnly(false); }} className="p-2 text-slate-400 hover:text-slate-700 hover:bg-slate-100 rounded-xl transition-all">
                <X size={18} />
              </button>
            </div>
            <form onSubmit={handleSubmit} className="p-6 space-y-4">

              {/* Registration Type Selector */}
              {!editingId && (
                <div className="flex bg-slate-100 p-1 rounded-xl">
                  <button
                    type="button"
                    disabled={isViewOnly}
                    onClick={() => {
                      setForm(f => ({ ...f, registrationType: "showroom" }));
                      setFormError("");
                    }}
                    className={`flex-1 py-2 text-xs font-bold rounded-lg transition-all flex items-center justify-center gap-1.5 ${
                      form.registrationType === "showroom"
                        ? "bg-white text-slate-900 shadow-sm"
                        : "text-slate-500 hover:text-slate-900"
                    }`}
                  >
                    <Building2 size={14} /> Showroom Bike
                  </button>
                  <button
                    type="button"
                    disabled={isViewOnly}
                    onClick={() => {
                      setForm(f => ({ ...f, registrationType: "external" }));
                      setExistingBike(null);
                      setFormError("");
                    }}
                    className={`flex-1 py-2 text-xs font-bold rounded-lg transition-all flex items-center justify-center gap-1.5 ${
                      form.registrationType === "external"
                        ? "bg-white text-slate-900 shadow-sm"
                        : "text-slate-500 hover:text-slate-900"
                    }`}
                  >
                    <User size={14} /> 3rd Party Customer
                  </button>
                </div>
              )}

              {/* Showroom Purchased Bike Search Flow */}
              {form.registrationType === "showroom" && (
                <>
                  {!editingId && !isViewOnly && (
                    <>
                      <div>
                        <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">Search By</label>
                        <select value={form.searchType} onChange={(e) => { setForm(f => ({ ...f, searchType: e.target.value, searchValue: "" })); setExistingBike(null); }}
                          disabled={isViewOnly}
                          className="w-full px-3.5 py-2.5 text-sm border border-slate-200 rounded-xl bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-900">
                          <option value="chasisNo">Chasis No</option>
                          <option value="registrationNo">Registration No</option>
                        </select>
                      </div>

                      <div>
                        <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">
                          {form.searchType === "chasisNo" ? "Chasis Number" : "Registration Number"}
                        </label>
                        <div className="flex gap-2">
                          <input type="text" value={form.searchValue}
                            disabled={isViewOnly}
                            onChange={(e) => setForm(f => ({ ...f, searchValue: e.target.value }))}
                            onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), handleSearchBike())}
                            placeholder={`Enter ${form.searchType === "chasisNo" ? "Chasis No" : "Reg No"}`}
                            className="flex-1 px-3.5 py-2.5 text-sm border border-slate-200 rounded-xl bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-900" />
                          <button type="button" onClick={handleSearchBike} disabled={searching || isViewOnly}
                            className="bg-slate-900 text-white text-xs font-bold px-4 py-2.5 rounded-xl hover:bg-slate-700 disabled:opacity-50 flex items-center gap-1.5">
                            {searching ? <Loader2 size={14} className="animate-spin" /> : <Search size={14} />}
                            Search
                          </button>
                        </div>
                      </div>
                    </>
                  )}

                  {existingBike && (
                    <div className="p-4 bg-emerald-50 border border-emerald-200 rounded-xl">
                      <p className="text-xs font-bold text-emerald-700 mb-1">✓ Linked Showroom Bike Purchase</p>
                      <p className="text-sm font-semibold text-emerald-900">{existingBike.bikeCompany} {existingBike.bikeModel}</p>
                      <p className="text-xs text-emerald-700">Chasis: {existingBike.chasisNo || "—"} | Reg: {form.registrationNo || existingBike.registrationNo || "AFR"}</p>
                    </div>
                  )}
                </>
              )}

              {/* 3rd Party Customer Bike Fields */}
              {form.registrationType === "external" && (
                <div className="space-y-3.5 p-4 bg-slate-50 border border-slate-200 rounded-xl">
                  <p className="text-xs font-bold text-slate-700 uppercase tracking-wider">👤 3rd Party Bike & Owner Details</p>
                  
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Customer / Owner Name</label>
                      <input type="text" value={form.customerName} disabled={isViewOnly} onChange={(e) => setForm(f => ({ ...f, customerName: e.target.value }))}
                        placeholder="e.g. Muhammad Ali"
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg bg-white disabled:bg-slate-100 disabled:text-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-900" />
                    </div>
                    <div>
                      <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Contact Phone</label>
                      <input type="text" value={form.customerPhone} disabled={isViewOnly} onChange={(e) => setForm(f => ({ ...f, customerPhone: e.target.value }))}
                        placeholder="e.g. 0300-1234567"
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg bg-white disabled:bg-slate-100 disabled:text-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-900" />
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Bike Company *</label>
                      <input type="text" value={form.bikeCompany} disabled={isViewOnly} onChange={(e) => setForm(f => ({ ...f, bikeCompany: e.target.value }))}
                        placeholder="e.g. Honda, Yamaha" required
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg bg-white disabled:bg-slate-100 disabled:text-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-900" />
                    </div>
                    <div>
                      <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Bike Model *</label>
                      <input type="text" value={form.bikeModel} disabled={isViewOnly} onChange={(e) => setForm(f => ({ ...f, bikeModel: e.target.value }))}
                        placeholder="e.g. CD 70 2024" required
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg bg-white disabled:bg-slate-100 disabled:text-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-900" />
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Chasis No</label>
                      <input type="text" value={form.chasisNo} disabled={isViewOnly} onChange={(e) => setForm(f => ({ ...f, chasisNo: e.target.value }))}
                        placeholder="e.g. ME123456"
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg bg-white disabled:bg-slate-100 disabled:text-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-900 font-mono" />
                    </div>
                    <div>
                      <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Engine No</label>
                      <input type="text" value={form.engineNo} disabled={isViewOnly} onChange={(e) => setForm(f => ({ ...f, engineNo: e.target.value }))}
                        placeholder="e.g. E987654"
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg bg-white disabled:bg-slate-100 disabled:text-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-900 font-mono" />
                    </div>
                  </div>
                </div>
              )}

              {/* Shared Registration & Agent Fee Fields */}
              {(form.registrationType === "external" || existingBike) && (
                <>
                  <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">Assigned Registration Number</label>
                    <input type="text" value={form.registrationNo} disabled={isViewOnly} onChange={(e) => setForm(f => ({ ...f, registrationNo: e.target.value }))}
                      placeholder="e.g. KHI-1234 (Leave blank or AFR if pending)"
                      className="w-full px-3.5 py-2.5 text-sm border border-slate-200 rounded-xl bg-slate-50 disabled:bg-slate-100 disabled:text-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-900 font-mono" />
                    {!isViewOnly && <p className="text-[11px] text-slate-400 mt-1">Entering a number here replaces AFR status once approved.</p>}
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">Agent / Letter Reference</label>
                    <input type="text" value={form.agentLetter} disabled={isViewOnly} onChange={(e) => setForm(f => ({ ...f, agentLetter: e.target.value }))}
                      placeholder="Agent name or letter reference" required
                      className="w-full px-3.5 py-2.5 text-sm border border-slate-200 rounded-xl bg-slate-50 disabled:bg-slate-100 disabled:text-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-900" />
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">Agent Fee / Cost (Rs.)</label>
                      <input type="number" value={form.agentTotalMoney} disabled={isViewOnly} onChange={(e) => setForm(f => ({ ...f, agentTotalMoney: e.target.value }))}
                        placeholder="e.g. 8500" required
                        className="w-full px-3.5 py-2.5 text-sm border border-slate-200 rounded-xl bg-slate-50 disabled:bg-slate-100 disabled:text-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-900" />
                    </div>
                    <div>
                      <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">Customer Charge (Rs.)</label>
                      <input type="number" value={form.customerTotalMoney} disabled={isViewOnly} onChange={(e) => setForm(f => ({ ...f, customerTotalMoney: e.target.value }))}
                        placeholder="e.g. 9000" required
                        className="w-full px-3.5 py-2.5 text-sm border border-slate-200 rounded-xl bg-slate-50 disabled:bg-slate-100 disabled:text-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-900" />
                    </div>
                  </div>

                  {form.agentTotalMoney !== "" && form.customerTotalMoney !== "" && (
                    <div className="p-3 bg-slate-100 rounded-xl flex items-center justify-between text-xs font-bold">
                      <span className="text-slate-600">Calculated Showroom Profit:</span>
                      <span className={`px-2 py-1 rounded-md ${Number(form.customerTotalMoney) - Number(form.agentTotalMoney) >= 0 ? "bg-emerald-100 text-emerald-800" : "bg-rose-100 text-rose-800"}`}>
                        {money(Number(form.customerTotalMoney) - Number(form.agentTotalMoney))}
                      </span>
                    </div>
                  )}

                  <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">Agent Advance Paid (Rs.)</label>
                    <input type="number" value={form.agentAdvance} disabled={isViewOnly} onChange={(e) => setForm(f => ({ ...f, agentAdvance: e.target.value }))}
                      placeholder="Advance paid to agent" required
                      className="w-full px-3.5 py-2.5 text-sm border border-slate-200 rounded-xl bg-slate-50 disabled:bg-slate-100 disabled:text-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-900" />
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">Registration Date &amp; Time</label>
                    <input type="datetime-local" value={form.registrationDateTime} disabled={isViewOnly} onChange={(e) => setForm(f => ({ ...f, registrationDateTime: e.target.value }))}
                      className="w-full px-3.5 py-2.5 text-sm border border-slate-200 rounded-xl bg-slate-50 disabled:bg-slate-100 disabled:text-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-900" />
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">Notes / Description</label>
                    <textarea value={form.description} disabled={isViewOnly} onChange={(e) => setForm(f => ({ ...f, description: e.target.value }))}
                      rows={3} placeholder="Additional notes..."
                      className="w-full px-3.5 py-2.5 text-sm border border-slate-200 rounded-xl bg-slate-50 disabled:bg-slate-100 disabled:text-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-900 resize-none" />
                  </div>
                </>
              )}

              {formError && (
                <p className="text-sm text-rose-600 bg-rose-50 border border-rose-200 rounded-xl px-4 py-2.5">{formError}</p>
              )}

              <div className="flex gap-3 pt-2">
                {!isViewOnly && canSubmit && (
                  <button type="submit" disabled={submitting}
                    className="flex-1 flex items-center justify-center gap-2 bg-slate-900 text-white text-sm font-bold py-3 rounded-xl hover:bg-slate-700 disabled:opacity-50">
                    {submitting ? <Loader2 size={16} className="animate-spin" /> : (editingId ? <Pencil size={16} /> : <Plus size={16} />)}
                    {editingId ? "Update Registration" : "Save Registration"}
                  </button>
                )}
                <button type="button" onClick={() => { setShowForm(false); setEditingId(null); setIsViewOnly(false); }}
                  className="flex-1 bg-slate-100 text-slate-600 text-sm font-bold py-3 rounded-xl hover:bg-slate-200">
                  {isViewOnly ? "Close" : "Cancel"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
