"use client";

import { useState, useEffect, useMemo } from "react";
import { ArrowLeft, Check, Plus, Loader2, RefreshCw, Search, FileDown, X, ClipboardList } from "lucide-react";
import { useRouter } from "next/navigation";

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;

function money(n) { return `Rs. ${Number(n || 0).toLocaleString()}`; }
function fmtDate(v) {
  if (!v) return "—";
  const d = v?.seconds ? new Date(v.seconds * 1000) : new Date(v);
  if (isNaN(d)) return "—";
  return d.toLocaleDateString("en-PK") + " " + d.toLocaleTimeString("en-PK", { hour: "2-digit", minute: "2-digit" });
}

function downloadRegPDF(item) {
  const win = window.open("", "_blank", "width=860,height=700");
  win.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8"/>
  <title>Registration — ${item.bikeCompany} ${item.bikeModel}</title>
  <style>*{box-sizing:border-box;margin:0;padding:0;font-family:'Segoe UI',Arial,sans-serif;}
  body{background:#fff;padding:28px;color:#1e293b;}
  @media print{.no-print{display:none!important;}}</style></head><body>
  <div class="no-print" style="text-align:right;margin-bottom:16px;">
    <button onclick="window.print()" style="padding:8px 20px;background:#0f172a;color:white;border:none;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;">🖨️ Print / Save PDF</button>
  </div>
  <div style="background:linear-gradient(135deg,#0f172a,#1e3a5f);color:white;padding:24px 28px;border-radius:14px;margin-bottom:22px;display:flex;justify-content:space-between;align-items:center;">
    <div>
      <div style="font-size:22px;font-weight:800;">🏍️ Ammar Autos</div>
      <div style="font-size:11px;opacity:.7;margin-top:4px;">Bike Showroom Management</div>
      <div style="margin-top:8px;display:inline-block;background:rgba(255,255,255,.15);padding:3px 10px;border-radius:20px;font-size:10px;font-weight:700;text-transform:uppercase;">Registration Record</div>
    </div>
    <div style="text-align:right;">
      <div style="font-size:10px;opacity:.7;">Status</div>
      <div style="font-size:14px;font-weight:700;">${item.paperReceived ? "✅ Paper Received" : "⏳ Pending"}</div>
    </div>
  </div>
  <table style="width:100%;border-collapse:collapse;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;">
    ${[
      ["Bike Company", item.bikeCompany],
      ["Bike Model", item.bikeModel],
      ["Chasis No", item.chasisNo],
      ["Registration No", item.registrationNo],
      ["Agent / Letter", item.agentLetter],
      ["Agent Total Money", money(item.agentTotalMoney)],
      ["Agent Advance", money(item.agentAdvance)],
      ["Description", item.description || "—"],
      ["Submitted", fmtDate(item.createdAt)],
    ].map(([l, v]) => `<tr style="border-bottom:1px solid #f1f5f9;">
      <td style="padding:10px 14px;font-size:12px;color:#64748b;font-weight:600;width:40%;">${l}</td>
      <td style="padding:10px 14px;font-size:12px;color:#1e293b;font-weight:500;">${v || "—"}</td>
    </tr>`).join("")}
  </table>
  <div style="margin-top:24px;padding-top:12px;border-top:1px solid #e2e8f0;text-align:center;font-size:11px;color:#94a3b8;">
    Generated by Ammar Autos — ${new Date().toLocaleDateString("en-PK", { year: "numeric", month: "long", day: "numeric" })}
  </div>
</body></html>`);
  win.document.close();
}

const emptyForm = {
  searchType: "chasisNo",
  searchValue: "",
  registrationDateTime: "",
  agentLetter: "",
  agentTotalMoney: "",
  agentAdvance: "",
  description: "",
};

export default function RegistrationPage() {
  const router = useRouter();
  const [registrations, setRegistrations] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [form, setForm] = useState(emptyForm);
  const [existingBike, setExistingBike] = useState(null);
  const [searching, setSearching] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [formError, setFormError] = useState("");

  const fetchRegistrations = async () => {
    setLoading(true);
    try {
      const res = await fetch(`${BASE_URL}/registration`);
      const data = await res.json();
      if (res.ok) setRegistrations(data.data || []);
    } catch (e) { console.error(e); }
    finally { setLoading(false); }
  };

  useEffect(() => { fetchRegistrations(); }, []);

  const filtered = useMemo(() => {
    if (!search.trim()) return registrations;
    const q = search.toLowerCase().trim();
    return registrations.filter(r =>
      r.bikeCompany?.toLowerCase().includes(q) ||
      r.bikeModel?.toLowerCase().includes(q) ||
      r.chasisNo?.toLowerCase().includes(q) ||
      r.registrationNo?.toLowerCase().includes(q) ||
      r.agentLetter?.toLowerCase().includes(q)
    );
  }, [registrations, search]);

  const handleSearchBike = async () => {
    if (!form.searchValue.trim()) return;
    setSearching(true);
    setExistingBike(null);
    setFormError("");
    try {
      const res = await fetch(`${BASE_URL}/registration/search-bike?searchType=${form.searchType}&searchValue=${encodeURIComponent(form.searchValue.trim())}`);
      const data = await res.json();
      if (data.found) {
        setExistingBike(data.data);
      } else {
        setFormError(`No purchase found with ${form.searchType === "chasisNo" ? "Chasis No" : "Reg No"}: "${form.searchValue}"`);
      }
    } catch (e) {
      setFormError("Search failed. Please try again.");
    } finally {
      setSearching(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!existingBike) return;
    setSubmitting(true);
    setFormError("");
    try {
      const payload = {
        searchType: form.searchType,
        searchValue: form.searchValue,
        bikeId: existingBike.id,
        bikeCompany: existingBike.bikeCompany || "",
        bikeModel: existingBike.bikeModel || "",
        chasisNo: existingBike.chasisNo || "",
        registrationNo: existingBike.registrationNo || "",
        registrationDateTime: form.registrationDateTime || new Date().toISOString(),
        agentLetter: form.agentLetter,
        agentTotalMoney: form.agentTotalMoney,
        agentAdvance: form.agentAdvance,
        description: form.description,
        paperReceived: false,
      };
      const res = await fetch(`${BASE_URL}/registration`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      if (res.ok) {
        setForm(emptyForm);
        setExistingBike(null);
        setShowForm(false);
        fetchRegistrations();
      } else {
        const d = await res.json();
        setFormError(d.message || "Failed to save");
      }
    } catch (e) {
      setFormError("Save failed. Please try again.");
    } finally {
      setSubmitting(false);
    }
  };

  const handleTogglePaper = async (id) => {
    try {
      await fetch(`${BASE_URL}/registration/${id}/receive-paper`, { method: "PATCH" });
      fetchRegistrations();
    } catch (e) { alert("Update failed"); }
  };

  const pending = registrations.filter(r => !r.paperReceived).length;
  const received = registrations.filter(r => r.paperReceived).length;

  return (
    <div className="min-h-screen bg-slate-50/50 text-slate-900 font-sans antialiased">
      {/* Header */}
      <header className="w-full bg-white border-b border-slate-200 sticky top-0 z-40 shadow-sm backdrop-blur-md">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="bg-slate-900 text-white p-2.5 rounded-xl shadow-md">
              <ClipboardList size={20} />
            </div>
            <div>
              <h1 className="text-xl font-bold tracking-tight text-slate-900">Ammar Autos</h1>
              <p className="text-xs text-slate-500 font-medium -mt-0.5">Registration Management</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <button onClick={fetchRegistrations} className="p-2 text-slate-400 hover:text-slate-900 hover:bg-slate-100 rounded-xl transition-colors"><RefreshCw size={16} /></button>
            <button
              onClick={() => { setShowForm(true); setForm(emptyForm); setExistingBike(null); setFormError(""); }}
              className="flex items-center gap-2 bg-slate-900 text-white text-sm font-semibold px-4 py-2.5 rounded-xl hover:bg-slate-700 transition-all shadow-md"
            >
              <Plus size={16} /> Add Registration
            </button>
            <button onClick={() => router.push("/dashboard")} className="flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-900 transition-colors">
              <ArrowLeft size={16} /> Back
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-6 py-8 space-y-6">

        {/* Stats */}
        <div className="grid grid-cols-3 gap-4">
          {[
            { label: "Total", value: registrations.length, color: "slate" },
            { label: "Pending", value: pending, color: "rose" },
            { label: "Received", value: received, color: "emerald" },
          ].map(s => (
            <div key={s.label} className="bg-white rounded-2xl border border-slate-200 shadow-sm p-5 text-center">
              <p className="text-xs font-bold uppercase tracking-wider text-slate-400">{s.label}</p>
              <p className={`text-3xl font-black mt-1 text-${s.color}-600`}>{s.value}</p>
            </div>
          ))}
        </div>

        {/* Search */}
        <div className="flex items-center gap-3 bg-white p-4 rounded-2xl border border-slate-200 shadow-sm">
          <Search size={18} className="text-slate-400" />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search by bike, chasis no, registration no, agent..."
            className="w-full text-sm bg-transparent outline-none"
          />
          {search && <button onClick={() => setSearch("")} className="text-slate-300 hover:text-slate-500"><X size={16} /></button>}
        </div>

        {/* List */}
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between">
            <h2 className="text-sm font-bold uppercase tracking-wider text-slate-500">Registration Records ({filtered.length})</h2>
          </div>
          {loading ? (
            <div className="flex justify-center py-16"><Loader2 size={28} className="animate-spin text-slate-400" /></div>
          ) : filtered.length === 0 ? (
            <div className="py-16 text-center">
              <ClipboardList size={40} className="mx-auto text-slate-300 mb-3" />
              <p className="text-sm text-slate-400 font-semibold">No registration records found.</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-slate-50 border-b border-slate-200">
                    {["#", "Bike", "Chasis No", "Reg No", "Agent", "Total Fee", "Advance", "Date", "Status", "Actions"].map(h => (
                      <th key={h} className="text-left px-4 py-3 text-xs font-bold uppercase tracking-wider text-slate-500 whitespace-nowrap">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {filtered.map((item, i) => (
                    <tr key={item.id} className={`border-b border-slate-100 transition-colors ${!item.paperReceived ? "bg-rose-50/40 hover:bg-rose-50" : "hover:bg-slate-50"}`}>
                      <td className="px-4 py-3 text-slate-400 font-medium">{i + 1}</td>
                      <td className="px-4 py-3 font-semibold text-slate-800 whitespace-nowrap">{item.bikeCompany} {item.bikeModel}</td>
                      <td className="px-4 py-3 text-slate-600 whitespace-nowrap">{item.chasisNo || "—"}</td>
                      <td className="px-4 py-3 text-slate-600 whitespace-nowrap">{item.registrationNo || "—"}</td>
                      <td className="px-4 py-3 text-slate-600 whitespace-nowrap">{item.agentLetter || "—"}</td>
                      <td className="px-4 py-3 font-semibold text-slate-800 whitespace-nowrap">{money(item.agentTotalMoney)}</td>
                      <td className="px-4 py-3 text-slate-600 whitespace-nowrap">{money(item.agentAdvance)}</td>
                      <td className="px-4 py-3 text-slate-500 whitespace-nowrap">{fmtDate(item.createdAt)}</td>
                      <td className="px-4 py-3">
                        <span className={`px-2.5 py-1 rounded-full text-xs font-bold ${item.paperReceived ? "bg-emerald-100 text-emerald-700" : "bg-rose-100 text-rose-700"}`}>
                          {item.paperReceived ? "Received" : "Pending"}
                        </span>
                      </td>
                      <td className="px-4 py-3">
                        <div className="flex items-center gap-1">
                          <button
                            onClick={() => handleTogglePaper(item.id)}
                            className={`p-1.5 rounded-lg transition-all ${item.paperReceived ? "text-emerald-600 hover:bg-emerald-50" : "text-rose-500 hover:bg-rose-50"}`}
                            title={item.paperReceived ? "Mark as Pending" : "Mark Paper Received"}
                          >
                            <Check size={14} />
                          </button>
                          <button
                            onClick={() => downloadRegPDF(item)}
                            className="p-1.5 text-slate-400 hover:text-emerald-600 hover:bg-emerald-50 rounded-lg transition-all"
                            title="Download PDF"
                          >
                            <FileDown size={14} />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </main>

      {/* Add Registration Modal */}
      {showForm && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between px-6 py-5 border-b border-slate-200">
              <h2 className="text-lg font-bold text-slate-900">Add Registration</h2>
              <button onClick={() => setShowForm(false)} className="p-2 text-slate-400 hover:text-slate-700 hover:bg-slate-100 rounded-xl transition-all">
                <X size={18} />
              </button>
            </div>
            <form onSubmit={handleSubmit} className="p-6 space-y-4">

              <div>
                <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">Search By</label>
                <select value={form.searchType} onChange={(e) => { setForm(f => ({ ...f, searchType: e.target.value, searchValue: "" })); setExistingBike(null); }}
                  className="w-full px-3.5 py-2.5 text-sm border border-slate-200 rounded-xl bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-900">
                  <option value="chasisNo">Chasis No</option>
                  <option value="registrationNo">Registration No</option>
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">
                  {form.searchType === "chasisNo" ? "Chasis Number" : "Registration Number"}
                </label>
                <div className="flex gap-2">
                  <input type="text" value={form.searchValue}
                    onChange={(e) => setForm(f => ({ ...f, searchValue: e.target.value }))}
                    onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), handleSearchBike())}
                    placeholder={`Enter ${form.searchType === "chasisNo" ? "Chasis No" : "Reg No"}`}
                    className="flex-1 px-3.5 py-2.5 text-sm border border-slate-200 rounded-xl bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-900" />
                  <button type="button" onClick={handleSearchBike} disabled={searching}
                    className="bg-slate-900 text-white text-xs font-bold px-4 py-2.5 rounded-xl hover:bg-slate-700 disabled:opacity-50 flex items-center gap-1.5">
                    {searching ? <Loader2 size={14} className="animate-spin" /> : <Search size={14} />}
                    Search
                  </button>
                </div>
              </div>

              {existingBike && (
                <div className="p-4 bg-emerald-50 border border-emerald-200 rounded-xl">
                  <p className="text-xs font-bold text-emerald-700 mb-1">✓ Bike Found in Purchases</p>
                  <p className="text-sm font-semibold text-emerald-900">{existingBike.bikeCompany} {existingBike.bikeModel}</p>
                  <p className="text-xs text-emerald-700">Chasis: {existingBike.chasisNo || "—"} | Reg: {existingBike.registrationNo || "—"}</p>
                </div>
              )}

              {existingBike && (
                <>
                  <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">Agent / Letter Given</label>
                    <input type="text" value={form.agentLetter} onChange={(e) => setForm(f => ({ ...f, agentLetter: e.target.value }))}
                      placeholder="Agent name or letter reference" required
                      className="w-full px-3.5 py-2.5 text-sm border border-slate-200 rounded-xl bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-900" />
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">Agent Total (Rs.)</label>
                      <input type="number" value={form.agentTotalMoney} onChange={(e) => setForm(f => ({ ...f, agentTotalMoney: e.target.value }))}
                        placeholder="Total fee" required
                        className="w-full px-3.5 py-2.5 text-sm border border-slate-200 rounded-xl bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-900" />
                    </div>
                    <div>
                      <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">Agent Advance (Rs.)</label>
                      <input type="number" value={form.agentAdvance} onChange={(e) => setForm(f => ({ ...f, agentAdvance: e.target.value }))}
                        placeholder="Advance paid" required
                        className="w-full px-3.5 py-2.5 text-sm border border-slate-200 rounded-xl bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-900" />
                    </div>
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">Registration Date &amp; Time</label>
                    <input type="datetime-local" value={form.registrationDateTime} onChange={(e) => setForm(f => ({ ...f, registrationDateTime: e.target.value }))}
                      className="w-full px-3.5 py-2.5 text-sm border border-slate-200 rounded-xl bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-900" />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">Notes / Description</label>
                    <textarea value={form.description} onChange={(e) => setForm(f => ({ ...f, description: e.target.value }))}
                      rows={3} placeholder="Additional notes..."
                      className="w-full px-3.5 py-2.5 text-sm border border-slate-200 rounded-xl bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-900 resize-none" />
                  </div>
                </>
              )}

              {formError && (
                <p className="text-sm text-rose-600 bg-rose-50 border border-rose-200 rounded-xl px-4 py-2.5">{formError}</p>
              )}

              <div className="flex gap-3 pt-2">
                {existingBike && (
                  <button type="submit" disabled={submitting}
                    className="flex-1 flex items-center justify-center gap-2 bg-slate-900 text-white text-sm font-bold py-3 rounded-xl hover:bg-slate-700 disabled:opacity-50">
                    {submitting ? <Loader2 size={16} className="animate-spin" /> : <Plus size={16} />}
                    Save Registration
                  </button>
                )}
                <button type="button" onClick={() => setShowForm(false)}
                  className="flex-1 bg-slate-100 text-slate-600 text-sm font-bold py-3 rounded-xl hover:bg-slate-200">
                  Cancel
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
